<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.5 Toxicokinetic Modeling | The inTelligence And Machine lEarning (TAME) Toolkit for Introductory Data Science, Chemical-Biological Analyses, Predictive Modeling, and Database Mining for Environmental Health Research</title>
  <meta name="description" content="2.5 Toxicokinetic Modeling | The inTelligence And Machine lEarning (TAME) Toolkit for Introductory Data Science, Chemical-Biological Analyses, Predictive Modeling, and Database Mining for Environmental Health Research" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="2.5 Toxicokinetic Modeling | The inTelligence And Machine lEarning (TAME) Toolkit for Introductory Data Science, Chemical-Biological Analyses, Predictive Modeling, and Database Mining for Environmental Health Research" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.5 Toxicokinetic Modeling | The inTelligence And Machine lEarning (TAME) Toolkit for Introductory Data Science, Chemical-Biological Analyses, Predictive Modeling, and Database Mining for Environmental Health Research" />
  
  
  

<meta name="author" content="Kyle R. Roell, Lauren E. Koval, Rebecca Boyles, Grace Patlewicz, Caroline Ring, Cynthia Rider, Cavin Ward-Caviness, David M. Reif, Ilona Jaspers, Rebecca C. Fry, and Julia E. Rager" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/Favicon_v1.png" type="image/x-icon" />
<link rel="prev" href="omics-analyses-and-systems-biology.html"/>
<link rel="next" href="read-across-toxicity-predictions.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="images/Data Training Icon for Top Left Bookdown_v2.png"><br></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="part"><span><b>Chapter 1 Introductory <br>Data Science</b></span></li>
<li class="chapter" data-level="" data-path="introduction-to-coding-in-r.html"><a href="introduction-to-coding-in-r.html"><i class="fa fa-check"></i>1.1 Introduction to Coding in R</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-coding-in-r.html"><a href="introduction-to-coding-in-r.html#introduction-to-training-module"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="introduction-to-coding-in-r.html"><a href="introduction-to-coding-in-r.html#r-packages"><i class="fa fa-check"></i>R Packages</a></li>
<li class="chapter" data-level="" data-path="introduction-to-coding-in-r.html"><a href="introduction-to-coding-in-r.html#scripting-basics"><i class="fa fa-check"></i>Scripting Basics</a></li>
<li class="chapter" data-level="" data-path="introduction-to-coding-in-r.html"><a href="introduction-to-coding-in-r.html#concluding-remarks-1"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-organization-basics.html"><a href="data-organization-basics.html"><i class="fa fa-check"></i>1.2 Data Organization Basics</a><ul>
<li class="chapter" data-level="" data-path="data-organization-basics.html"><a href="data-organization-basics.html#introduction-to-training-module-1"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="data-organization-basics.html"><a href="data-organization-basics.html#data-manipulation-using-base-r"><i class="fa fa-check"></i>Data Manipulation using Base R</a></li>
<li class="chapter" data-level="" data-path="data-organization-basics.html"><a href="data-organization-basics.html#introduction-to-tidyverse"><i class="fa fa-check"></i>Introduction to Tidyverse</a></li>
<li class="chapter" data-level="" data-path="data-organization-basics.html"><a href="data-organization-basics.html#concluding-remarks-2"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="finding-and-visualizing-data-trends.html"><a href="finding-and-visualizing-data-trends.html"><i class="fa fa-check"></i>1.3 Finding and Visualizing Data Trends</a><ul>
<li class="chapter" data-level="" data-path="finding-and-visualizing-data-trends.html"><a href="finding-and-visualizing-data-trends.html#introduction-to-training-module-2"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="finding-and-visualizing-data-trends.html"><a href="finding-and-visualizing-data-trends.html#basic-data-analysis"><i class="fa fa-check"></i>Basic Data Analysis</a></li>
<li class="chapter" data-level="" data-path="finding-and-visualizing-data-trends.html"><a href="finding-and-visualizing-data-trends.html#regression-modeling"><i class="fa fa-check"></i>Regression Modeling</a></li>
<li class="chapter" data-level="" data-path="finding-and-visualizing-data-trends.html"><a href="finding-and-visualizing-data-trends.html#categorical-data-analysis"><i class="fa fa-check"></i>Categorical Data Analysis</a></li>
<li class="chapter" data-level="" data-path="finding-and-visualizing-data-trends.html"><a href="finding-and-visualizing-data-trends.html#concluding-remarks-3"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html"><i class="fa fa-check"></i>1.4 High-Dimensional Data Visualizations</a><ul>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html#introduction-to-training-module-3"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html#high-dimensional-data-visualizations-1"><i class="fa fa-check"></i>High-Dimensional Data Visualizations</a></li>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html#density-plot-visualizations"><i class="fa fa-check"></i>Density Plot Visualizations</a></li>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html#ggally-visualizations"><i class="fa fa-check"></i>GGally Visualizations</a></li>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html#boxplot-visualizations"><i class="fa fa-check"></i>Boxplot Visualizations</a></li>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html#correlation-plot-visualizations"><i class="fa fa-check"></i>Correlation Plot Visualizations</a></li>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html#hierarchical-clustering-visualizations"><i class="fa fa-check"></i>Hierarchical Clustering Visualizations</a><ul>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html#heat-map-visualizations"><i class="fa fa-check"></i>Heat map Visualizations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="high-dimensional-data-visualizations.html"><a href="high-dimensional-data-visualizations.html#concluding-remarks-4"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html"><i class="fa fa-check"></i>1.5 FAIR Data Management Practices</a><ul>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#introduction-to-training-module-4"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#introduction-to-fair"><i class="fa fa-check"></i>Introduction to FAIR</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#breaking-down-fair-letter-by-letter"><i class="fa fa-check"></i>Breaking Down FAIR, Letter-by-Letter</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#data-repositories-for-sharing-of-data"><i class="fa fa-check"></i>Data Repositories for Sharing of Data</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#helpful-resources-on-fair"><i class="fa fa-check"></i>Helpful Resources on FAIR</a></li>
<li class="chapter" data-level="" data-path="fair-data-management-practices.html"><a href="fair-data-management-practices.html#concluding-remarks-5"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Chapter 2 Chemical-<br>Biological Analyses <br>and Predictive Modeling</b></span></li>
<li class="chapter" data-level="" data-path="dose-response-modeling.html"><a href="dose-response-modeling.html"><i class="fa fa-check"></i>2.1 Dose-Response Modeling</a><ul>
<li class="chapter" data-level="" data-path="dose-response-modeling.html"><a href="dose-response-modeling.html#introduction-to-training-module-5"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="dose-response-modeling.html"><a href="dose-response-modeling.html#plotting-data-in-dose-response"><i class="fa fa-check"></i>Plotting Data in Dose-Response</a></li>
<li class="chapter" data-level="" data-path="dose-response-modeling.html"><a href="dose-response-modeling.html#dose-response-curve-fitting"><i class="fa fa-check"></i>Dose-Response Curve Fitting</a></li>
<li class="chapter" data-level="" data-path="dose-response-modeling.html"><a href="dose-response-modeling.html#comparing-curve-fits"><i class="fa fa-check"></i>Comparing Curve Fits</a></li>
<li class="chapter" data-level="" data-path="dose-response-modeling.html"><a href="dose-response-modeling.html#curve-fitting-example"><i class="fa fa-check"></i>Curve Fitting Example</a></li>
<li class="chapter" data-level="" data-path="dose-response-modeling.html"><a href="dose-response-modeling.html#deriving-benchmark-dose"><i class="fa fa-check"></i>Deriving Benchmark Dose</a></li>
<li class="chapter" data-level="" data-path="dose-response-modeling.html"><a href="dose-response-modeling.html#concluding-remarks-6"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="machine-learning-and-predictive-modeling.html"><a href="machine-learning-and-predictive-modeling.html"><i class="fa fa-check"></i>2.2 Machine Learning and Predictive Modeling</a><ul>
<li class="chapter" data-level="" data-path="machine-learning-and-predictive-modeling.html"><a href="machine-learning-and-predictive-modeling.html#introduction-to-training-module-6"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="machine-learning-and-predictive-modeling.html"><a href="machine-learning-and-predictive-modeling.html#k-means-analysis"><i class="fa fa-check"></i>K-means Analysis</a></li>
<li class="chapter" data-level="" data-path="machine-learning-and-predictive-modeling.html"><a href="machine-learning-and-predictive-modeling.html#principal-component-analysis"><i class="fa fa-check"></i>Principal Component Analysis</a></li>
<li class="chapter" data-level="" data-path="machine-learning-and-predictive-modeling.html"><a href="machine-learning-and-predictive-modeling.html#combining-k-means-with-pca"><i class="fa fa-check"></i>Combining K-Means with PCA</a></li>
<li class="chapter" data-level="" data-path="machine-learning-and-predictive-modeling.html"><a href="machine-learning-and-predictive-modeling.html#concluding-remarks-7"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="mixtures-analyses.html"><a href="mixtures-analyses.html"><i class="fa fa-check"></i>2.3 Mixtures Analyses</a><ul>
<li class="chapter" data-level="" data-path="mixtures-analyses.html"><a href="mixtures-analyses.html#introduction-to-training-module-7"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="mixtures-analyses.html"><a href="mixtures-analyses.html#chemistry-based-approach"><i class="fa fa-check"></i>Chemistry-based Approach</a></li>
<li class="chapter" data-level="" data-path="mixtures-analyses.html"><a href="mixtures-analyses.html#toxicity-based-approach"><i class="fa fa-check"></i>Toxicity-based Approach</a></li>
<li class="chapter" data-level="" data-path="mixtures-analyses.html"><a href="mixtures-analyses.html#comparing-results"><i class="fa fa-check"></i>Comparing Results</a></li>
<li class="chapter" data-level="" data-path="mixtures-analyses.html"><a href="mixtures-analyses.html#concluding-remarks-8"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html"><i class="fa fa-check"></i>2.4 -Omics Analyses and Systems Biology</a><ul>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html#the-field-of--omics"><i class="fa fa-check"></i>The Field of “-Omics”</a></li>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html#transcriptomics"><i class="fa fa-check"></i>Transcriptomics</a></li>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html#introduction-to-training-module-8"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html#transcriptomics-data-qaqc"><i class="fa fa-check"></i>Transcriptomics Data QA/QC</a></li>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html#statistical-analysis-of-gene-expression"><i class="fa fa-check"></i>Statistical Analysis of Gene Expression</a></li>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html#ma-plots"><i class="fa fa-check"></i>MA Plots</a></li>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html#volcano-plots"><i class="fa fa-check"></i>Volcano Plots</a></li>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html#pathway-enrichment-analysis"><i class="fa fa-check"></i>Pathway Enrichment Analysis</a></li>
<li class="chapter" data-level="" data-path="omics-analyses-and-systems-biology.html"><a href="omics-analyses-and-systems-biology.html#concluding-remarks-9"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html"><i class="fa fa-check"></i>2.5 Toxicokinetic Modeling</a><ul>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#introduction-to-toxicokinetic-modeling"><i class="fa fa-check"></i>Introduction to Toxicokinetic Modeling</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#introduction-to-training-module-9"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#data-and-models-used-in-toxicokinetic-modeling-tk"><i class="fa fa-check"></i>Data and Models used in Toxicokinetic Modeling (TK)</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#calculating-steady-state-concentration"><i class="fa fa-check"></i>Calculating steady-state concentration</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#reverse-toxicokinetics"><i class="fa fa-check"></i>Reverse Toxicokinetics</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#monte-carlo-approach"><i class="fa fa-check"></i>Monte Carlo Approach</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#chemical-specific-example"><i class="fa fa-check"></i>Chemical-Specific Example</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#calculating-bioactivity-exposure-ratios-bers"><i class="fa fa-check"></i>Calculating Bioactivity-Exposure Ratios (BERs)</a></li>
<li class="chapter" data-level="" data-path="toxicokinetic-modeling.html"><a href="toxicokinetic-modeling.html#concluding-remarks-10"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="read-across-toxicity-predictions.html"><a href="read-across-toxicity-predictions.html"><i class="fa fa-check"></i>2.6 Read-Across Toxicity Predictions</a><ul>
<li class="chapter" data-level="" data-path="read-across-toxicity-predictions.html"><a href="read-across-toxicity-predictions.html#introduction-to-chemical-read-across"><i class="fa fa-check"></i>Introduction to Chemical Read-Across</a></li>
<li class="chapter" data-level="" data-path="read-across-toxicity-predictions.html"><a href="read-across-toxicity-predictions.html#introduction-to-training-module-10"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="read-across-toxicity-predictions.html"><a href="read-across-toxicity-predictions.html#read-across-example-analysis"><i class="fa fa-check"></i>Read Across Example Analysis</a></li>
<li class="chapter" data-level="" data-path="read-across-toxicity-predictions.html"><a href="read-across-toxicity-predictions.html#calculating-chemical-similarities"><i class="fa fa-check"></i>Calculating Chemical Similarities</a></li>
<li class="chapter" data-level="" data-path="read-across-toxicity-predictions.html"><a href="read-across-toxicity-predictions.html#chemical-read-across-to-predict-acute-toxicity"><i class="fa fa-check"></i>Chemical Read-Across to Predict Acute Toxicity</a></li>
<li class="chapter" data-level="" data-path="read-across-toxicity-predictions.html"><a href="read-across-toxicity-predictions.html#concluding-remarks-11"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Chapter 3 Environmental <br>Health Database Mining</b></span></li>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html"><i class="fa fa-check"></i>3.1 Comparative Toxicogenomics Database</a><ul>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html#introduction-to-training-module-11"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html#ctd-data-in-r"><i class="fa fa-check"></i>CTD Data in R</a></li>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html#identifying-genes-under-epigenetic-control"><i class="fa fa-check"></i>Identifying Genes under Epigenetic Control</a></li>
<li class="chapter" data-level="" data-path="comparative-toxicogenomics-database.html"><a href="comparative-toxicogenomics-database.html#concluding-remarks-12"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html"><i class="fa fa-check"></i>3.2 Gene Expression Omnibus</a><ul>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#introduction-to-training-module-12"><i class="fa fa-check"></i>Introduction to Training Module</a><ul>
<li><a href="gene-expression-omnibus.html#training-modules-environmental-health-questions-7">Training Module’s <strong>Environmental Health Questions</strong></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#geo-data-in-r"><i class="fa fa-check"></i>GEO Data in R</a></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#visualizing-data"><i class="fa fa-check"></i>Visualizing Data</a></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#statistical-analyses"><i class="fa fa-check"></i>Statistical Analyses</a></li>
<li class="chapter" data-level="" data-path="gene-expression-omnibus.html"><a href="gene-expression-omnibus.html#concluding-remarks-13"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html"><i class="fa fa-check"></i>3.3 Database Integration: Air Quality, Mortality, and Environmental Justice Data</a><ul>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#introduction-to-exposure-and-health-databases-used-in-this-module"><i class="fa fa-check"></i>Introduction to Exposure and Health Databases used in this Module</a></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#introduction-to-training-module-13"><i class="fa fa-check"></i>Introduction to Training Module</a></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#population-weighted-vs-unweighted-exposures"><i class="fa fa-check"></i>Population-weighted vs Unweighted Exposures</a></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#regression-modeling-1"><i class="fa fa-check"></i>Regression Modeling</a></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#environmental-justice-considerations"><i class="fa fa-check"></i>Environmental Justice Considerations</a></li>
<li class="chapter" data-level="" data-path="database-integration-air-quality-mortality-and-environmental-justice-data.html"><a href="database-integration-air-quality-mortality-and-environmental-justice-data.html#concluding-remarks-14"><i class="fa fa-check"></i>Concluding Remarks</a></li>
</ul></li>
<li class="part"><span><b>Additional Resources</b></span></li>
<li class="chapter" data-level="" data-path="resources.html"><a href="resources.html"><i class="fa fa-check"></i>Resources</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The inTelligence And Machine lEarning (TAME) Toolkit for Introductory Data Science, Chemical-Biological Analyses, Predictive Modeling, and Database Mining for Environmental Health Research</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="toxicokinetic-modeling" class="section level1">
<h1>2.5 Toxicokinetic Modeling</h1>
<p>This training module was developed by Dr. Caroline Ring</p>
<p><em>Disclaimer: The views expressed in this document are those of the author and do not necessarily reflect the views or policies of the U.S. EPA.</em></p>
<div id="introduction-to-toxicokinetic-modeling" class="section level2">
<h2>Introduction to Toxicokinetic Modeling</h2>
<p>To understand what toxicokinetic modeling is, consider the following scenario:
<img src="Module2_5/Module2_5_TK_Intro_Image.png" width="1292" /></p>
<p>Simply put, toxicokinetics answers these questions by describing “what the body does to the chemical” after an exposure scenario.</p>
<p>More technically, <strong>toxicokinetic modeling</strong> refers to the evaluation of the uptake and disposition of a chemical in the body.</p>
<div id="notes-on-terminology" class="section level4">
<h4>Notes on terminology</h4>
<p>Pharmacokinetics (PK) is a synonym for toxicokinetics (TK). They are often used interchangeably. PK connotes pharmaceuticals; TK connotes environmental chemicals – but those connotations are weak.</p>
<p>A common abbreviation that you will also see in this research field is <strong>ADME</strong>, which stands for:</p>
<ul>
<li><strong>Absorption:</strong> How does the chemical get absorbed into the body tissues?<br />
</li>
<li><strong>Distribution:</strong> Where does the chemical go inside the body?<br />
</li>
<li><strong>Metabolism:</strong> How do enzymes in the body break apart the chemical molecules?<br />
</li>
<li><strong>Excretion:</strong> How does the chemical leave the body?</li>
</ul>
<p>To place this term into the context of TK, TK models describe ADME mathematically by representing the body as compartments and flows.</p>
</div>
<div id="types-of-tk-models" class="section level4">
<h4>Types of TK models</h4>
<p>TK models describe the body mathematically as one or more “compartments” connected by “flows.” The compartments represent organs or tissues. Using mass balance equations, the amount or concentration of chemical in each compartment is described as a function of time.</p>
<p>Types of models discussed throughout this training module are described here.</p>
</div>
<div id="compartment-model" class="section level4">
<h4>1 Compartment Model</h4>
<p>The simplest TK model is a 1-compartment model, where the body is assumed to be one big well-mixed compartment.</p>
</div>
<div id="compartment-model-1" class="section level4">
<h4>3 Compartment Model</h4>
<p>A 3-compartment model mathematically incorporates three distinct body compartments, that can exhibit different parameters contributing to their individual mass balance. Commonly used compartments in 3-compartment modeling can include tissues like blood plasma, liver, gut, kidney, and/or ‘rest of body’ terms; though the specific compartments included depend on the chemical under evaluation, exposure scenario, and modeling assumptions.</p>
</div>
<div id="pbtk-model" class="section level4">
<h4>PBTK Model</h4>
<p>A physiologically-based TK (PBTK) model incorporates compartments and flows that represent real physiological quantities (as opposed to the aforementioned empirical 1- and 3-compartment models). PBTK models have more parameters overall, including parameters representing physiological quantities that are known <em>a priori</em> based on studies of anatomy. The only PBTK model parameters that need to be estimated for each new chemical are parameters representing chemical-body interactions, which can include the following:</p>
<ul>
<li>Rate of hepatic metabolism of chemical: How fast does liver break down chemical?</li>
<li>Plasma protein binding: How tightly does the chemical bind to proteins in blood plasma? Liver may not be able to break down chemical that is bound to plasma protein.</li>
<li>Blood:tissue partition coefficients: Assuming chemical diffuses between blood and other tissues very fast compared to the rate of blood flow, the ratio of concentration in blood to concentration in each tissue is approximately constant = partition coefficient.</li>
<li>Rate of active transport into/out of a tissue: If chemical moves between blood and tissues not just by passive diffusion, but by cells actively transporting it in or out of the tissue</li>
<li>Binding to other tissues: Some chemical may be bound inside a tissue and not available for diffusion or transport in/out</li>
</ul>
<p>Types of TK modeling can also fall into the following major categories:</p>
<ol style="list-style-type: decimal">
<li><strong>Forward TK Modeling:</strong> Where external exposure doses are converted into internal doses (or concentrations of chemicals/drugs in one or more body tissues of interest).</li>
<li><strong>Reverse TK Modeling:</strong> The reverse of the above, where internal doses are converted into external exposure doses.</li>
</ol>
</div>
<div id="other-tk-modeling-resources" class="section level4">
<h4>Other TK modeling resources</h4>
<p>For further information on TK modeling background, math, and example models, there are additional resources online including a helpful course website on <a href="https://www.boomer.org/c/p4/">Basic Pharmacokinetics</a> by Dr. Bourne.</p>
</div>
</div>
<div id="introduction-to-training-module-9" class="section level2">
<h2>Introduction to Training Module</h2>
<p>This module serves as an example to guide trainees through the basics of toxicokinetic (TK) modeling and how this type of modeling can be used in the high-throughput setting for environmental health research applications.</p>
<p>In this activity, the capabilities of a high-throughput toxicokinetic modeling package titled ‘httk’ are demonstrated on a suite of environmentally relevant chemicals. The httk R package implements high-throughput toxicokinetic modeling (hence, ‘httk’), including a generic physiologically based toxicokinetic (PBTK) model as well as tables of chemical-specific parameters needed to solve the model for hundreds of chemicals. In this activity, the capabilities of ‘httk’ are demonstrated and explored. Example modeling estimates are produced for the high interest environmental chemical, bisphenol-A. Then, an example script is provided to derive the plasma concentration at steady state for an example environmental chemical, bisphenol-A.</p>
<p>The concept of reverse toxicokinetics is explained and demonstrated, again using bisphenol-A as an example chemical.</p>
<p>This module then demonstrates the derivation of the bioactivity-exposure ratio (BER) across many chemicals leveraging the capabilities of httk, while incorporating exposure measures. BERs are particularly useful in the evaluation of chemical risk, as they take into account both toxicity (i.e., <em>in vitro</em> potency) and exposure rates, the two essential components used in risk calculations for chemical safety and prioritization evaluations. Therefore, the estimates of both potency and exposure and needed to calculate BERs, which are described in this training module.</p>
<p>For potency estimates, the ToxCast high-throughput screening library is introduced as an example high-throughput dataset to carry out in vitro to in vivo extrapolation (IVIVE) modeling through httk. ToxCast activity concentrations that elicit 50% maximal bioactivity (AC50) are uploaded and organized as inputs, and then the tenth percentile ToxCast AC50 is calculated for each chemical (in other words, across all ToxCast screening assays, the tenth percentile of AC50 values were carried forward). These concentration estimates then serve as concentration estimates for potency. For exposure estimates, previously generated exposure estimates that have been inferred from CDC NHANES urinary biomonitoring data are used.</p>
<p>The bioactivity-exposure ratio (BER) is then calculated across chemicals with both potency and exposure estimate information. This ratio is simply calculated as the ratio of the lower-end equivalent dose (for the most-sensitive 5% of the population) divided by the upper-end estimated exposure (here, the upper bound on the inferred population median exposure). Chemicals are then ranked based on resulting BERs and visualized through plots. The importance of these chemical prioritization are then discussed in relation to environmental health research and corresponding regulatory decisions.</p>
<div id="training-modules-environmental-health-questions-4" class="section level4">
<h4>Training Module’s <strong>Environmental Health Questions</strong></h4>
<p>This training module was specifically developed to answer the following environmental health questions:</p>
<ol style="list-style-type: decimal">
<li>After solving the TK model that evaluates bisphenol-A, what is the maximum concentration of bisphenol-A estimated to occur in human plasma, after 1 exposure dose of 1 mg/kg/day?</li>
<li>After solving the TK model that evaluates bisphenol-A, what is the steady-state concentration of bisphenol-A estimated to occur in human plasma, for a long-term oral infusion dose of 1 mg/kg/day?</li>
<li>What is the predicted range of bisphenol-A concentrations in plasma that can occur in a human population, assuming a long-term exposure rate of 1 mg/kg/day and steady-state conditions? Provide estimates at the 5th, 50th, and 95th percentile?</li>
<li>Considering the chemicals evaluated in the above TK modeling example, do the <span class="math inline">\(C_{ss}\)</span>-dose slope distributions become wider as the median <span class="math inline">\(C_{ss}\)</span>-dose slope increases?</li>
<li>How many chemicals have available AC50 values to evaluate in the current ToxCast/Tox21 high-throughput screening database?</li>
<li>What are the chemicals with the ten lowest predicted equivalent doses (for tenth-percentile ToxCast AC50s), for the most-sensitive 5% of the population?</li>
<li>Based on httk modeling estimates, are chemicals with higher bioactivity-exposure ratios always less potent than chemicals with lower bioactivity-exposure ratios?</li>
<li>Based on httk modeling estimates, do chemicals with higher bioactivity-exposure ratios always have lower estimated exposures than chemicals with lower bioactivity-exposure ratios?</li>
<li>How are chemical prioritization results different when using only hazard information vs. only exposure information vs. bioactivity-exposure ratios?</li>
</ol>
</div>
<div id="script-preparations-6" class="section level4">
<h4>Script Preparations</h4>
</div>
<div id="cleaning-the-global-environment-6" class="section level4">
<h4>Cleaning the global environment</h4>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="toxicokinetic-modeling.html#cb382-1"></a><span class="kw">rm</span>(<span class="dt">list=</span><span class="kw">ls</span>())</span></code></pre></div>
</div>
<div id="set-your-working-directory-8" class="section level4">
<h4>Set your working directory</h4>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="toxicokinetic-modeling.html#cb383-1"></a><span class="kw">setwd</span>(<span class="st">&quot;/filepath to where your input files are&quot;</span>)</span></code></pre></div>
</div>
<div id="installing-required-r-packages-6" class="section level4">
<h4>Installing required R packages</h4>
<p>If you already have these packages installed, you can skip this step, or you can run the below code which checks installation status for you:</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="toxicokinetic-modeling.html#cb384-1"></a><span class="cf">if</span>(<span class="op">!</span><span class="kw">nzchar</span>(<span class="kw">system.file</span>(<span class="dt">package =</span> <span class="st">&quot;ggplot2&quot;</span>))){</span>
<span id="cb384-2"><a href="toxicokinetic-modeling.html#cb384-2"></a>  <span class="kw">install.packages</span>(<span class="st">&quot;ggplot2&quot;</span>)}</span>
<span id="cb384-3"><a href="toxicokinetic-modeling.html#cb384-3"></a><span class="cf">if</span>(<span class="op">!</span><span class="kw">nzchar</span>(<span class="kw">system.file</span>(<span class="dt">package =</span> <span class="st">&quot;reshape2&quot;</span>))){</span>
<span id="cb384-4"><a href="toxicokinetic-modeling.html#cb384-4"></a>  <span class="kw">install.packages</span>(<span class="st">&quot;reshape2&quot;</span>)}</span>
<span id="cb384-5"><a href="toxicokinetic-modeling.html#cb384-5"></a><span class="cf">if</span>(<span class="op">!</span><span class="kw">nzchar</span>(<span class="kw">system.file</span>(<span class="dt">package =</span> <span class="st">&quot;stringr&quot;</span>))){</span>
<span id="cb384-6"><a href="toxicokinetic-modeling.html#cb384-6"></a>  <span class="kw">install.packages</span>(<span class="st">&quot;stringr&quot;</span>)}</span>
<span id="cb384-7"><a href="toxicokinetic-modeling.html#cb384-7"></a><span class="cf">if</span>(<span class="op">!</span><span class="kw">nzchar</span>(<span class="kw">system.file</span>(<span class="dt">package =</span> <span class="st">&quot;httk&quot;</span>))){</span>
<span id="cb384-8"><a href="toxicokinetic-modeling.html#cb384-8"></a>  <span class="kw">install.packages</span>(<span class="st">&quot;httk&quot;</span>)}</span>
<span id="cb384-9"><a href="toxicokinetic-modeling.html#cb384-9"></a><span class="cf">if</span>(<span class="op">!</span><span class="kw">nzchar</span>(<span class="kw">system.file</span>(<span class="dt">package =</span> <span class="st">&quot;eulerr&quot;</span>))){</span>
<span id="cb384-10"><a href="toxicokinetic-modeling.html#cb384-10"></a>  <span class="kw">install.packages</span>(<span class="st">&quot;eulerr&quot;</span>)}</span></code></pre></div>
</div>
<div id="loading-r-packages-required-for-this-session-5" class="section level4">
<h4>Loading R packages required for this session</h4>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="toxicokinetic-modeling.html#cb385-1"></a><span class="kw">library</span>(ggplot2) <span class="co"># ggplot2 will be used to generate associated graphics</span></span>
<span id="cb385-2"><a href="toxicokinetic-modeling.html#cb385-2"></a><span class="kw">library</span>(reshape2) <span class="co"># reshape2 will be used to organize and transform datasets</span></span>
<span id="cb385-3"><a href="toxicokinetic-modeling.html#cb385-3"></a><span class="kw">library</span>(stringr) <span class="co"># stringr will be used to aid in various data manipulation steps through this module</span></span>
<span id="cb385-4"><a href="toxicokinetic-modeling.html#cb385-4"></a><span class="kw">library</span>(httk) <span class="co"># httk package will be used to carry out all toxicokinetic modeling steps</span></span>
<span id="cb385-5"><a href="toxicokinetic-modeling.html#cb385-5"></a><span class="kw">library</span>(eulerr) <span class="co">#eulerr package will be used to generate Venn/Euler diagram graphics</span></span></code></pre></div>
<p>For more information on the <strong>ggplot2 package</strong>, see its associated <a href="https://cran.r-project.org/web/packages/ggplot2/index.html">CRAN webpage</a> and <a href="https://www.rdocumentation.org/packages/ggplot2/versions/3.3.5">RDocumentation webpage</a>.</p>
<p>For more information on the <strong>reshape2 package</strong>, see its associated <a href="https://cran.r-project.org/web/packages/reshape2/index.html">CRAN webpage</a> and <a href="https://www.rdocumentation.org/packages/reshape2/versions/1.4.4">RDocumentation webpage</a>.</p>
<p>For more information on the <strong>stringr package</strong>, see its associated <a href="https://cran.r-project.org/web/packages/stringr/index.html">CRAN webpage</a> and <a href="https://www.rdocumentation.org/packages/stringr/versions/1.4.0">RDocumentation webpage</a>.</p>
<p>For more information on the <strong>httk package</strong>, see its associated <a href="https://cran.r-project.org/web/packages/httk/index.html">CRAN webpage</a> and parent publication by <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6134854/">Pearce et al. (2017)</a>.</p>
</div>
<div id="more-information-on-the-httk-package" class="section level4">
<h4>More information on the httk package</h4>
<p>You can see an overview of the <code>httk</code> package by typing <code>?httk</code> at the R command line.</p>
<p>You can see a browsable index of all functions in the <code>httk</code> package by typing <code>help(package="httk")</code> at the R command line.</p>
<p>You can see a browsable list of vignettes by typing <code>browseVignettes("httk")</code> at the R command line. (Please note that some of these vignettes were written using older versions of the package and may no longer work as written – specifically the Ring (2017) vignette, which I wrote back in 2016. The <code>httk</code> team is actively working on updating these.)</p>
<p>You can get information about any function in <code>httk</code>, or indeed any function in any R package, by typing <code>help()</code> and placing the function name in quotation marks inside the parentheses. For example, to get information about the <code>httk</code> function <code>solve_model()</code>, type this:</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="toxicokinetic-modeling.html#cb386-1"></a><span class="kw">help</span>(<span class="st">&quot;solve_model&quot;</span>)</span></code></pre></div>
</div>
</div>
<div id="data-and-models-used-in-toxicokinetic-modeling-tk" class="section level2">
<h2>Data and Models used in Toxicokinetic Modeling (TK)</h2>
<div id="common-models-used-in-tk-modeling" class="section level4">
<h4>Common Models used in TK Modeling</h4>
<!-- , that are Provided as Built-in Models in 'httk' -->
<p>There are five TK models currently built into <code>httk</code>. They are:</p>
<ul>
<li><code>pbtk</code>: A physiologically-based TK model with oral absorption. Contains the following compartments: gutlumen, gut, liver, kidneys, veins, arteries, lungs, and the rest of the body. Chemical is metabolized by the liver and excreted by the kidneys via glomerular filtration.</li>
<li><code>gas_pbtk</code>: A PBTK model with absorption via inhalation. Contains the same compartments as <code>pbtk</code>.</li>
<li><code>1compartment</code>: A simple one-compartment TK model with oral absorption.</li>
<li><code>3compartment</code>: A three-compartment TK model with oral absorption. Compartments are gut, liver, and rest of body.</li>
<li><code>3compartmentss</code>: The steady-state solution to the 3-compartment model under an assumption of constant infusion dosing, without considering tissue partitioning. This was the first <code>httk</code> model (see Wambaugh et al. 2015, Wetmore et al. 2012, Rotroff et al. 2010).</li>
</ul>
</div>
<div id="chemical-specific-tk-data-built-into-httk" class="section level4">
<h4>Chemical-Specific TK Data Built Into ‘httk’</h4>
<p>Each of these TK models has chemical-specific parameters. The chemical-specific TK information needed to parameterize these models is built into <code>httk</code>, in the form of a built-in lookup table in a data.frame called <code>chem.physical_and_invitro.data</code>. This lookup table means that in order to run a TK model for a particular chemical, you only need to specify the chemical.</p>
<p>Look at the first few rows of this data.frame to see everything that’s in there (it is a lot of information).</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="toxicokinetic-modeling.html#cb387-1"></a><span class="kw">head</span>(chem.physical_and_invitro.data)</span></code></pre></div>
<pre><code>##                                                         Compound        CAS
## 2971-36-0  2,2-bis(4-hydroxyphenyl)-1,1,1-trichloroethane (hpte)  2971-36-0
## 94-75-7                                                    2,4-d    94-75-7
## 94-82-6                                                   2,4-db    94-82-6
## 90-43-7                                           2-phenylphenol    90-43-7
## 1007-28-9                                 6-desisopropylatrazine  1007-28-9
## 71751-41-2                                             Abamectin 71751-41-2
##            CAS.Checksum        DTXSID     Formula
## 2971-36-0          TRUE DTXSID8022325 C14H11Cl3O2
## 94-75-7            TRUE DTXSID0020442   C8H6Cl2O3
## 94-82-6            TRUE DTXSID7024035 C10H10Cl2O3
## 90-43-7            TRUE DTXSID2021151     C12H10O
## 1007-28-9          TRUE DTXSID0037495    C5H8ClN5
## 71751-41-2         TRUE DTXSID8023892           -
##                                         SMILES.desalt
## 2971-36-0  OC1=CC=C(C=C1)C(C1=CC=C(O)C=C1)C(Cl)(Cl)Cl
## 94-75-7                   OC(=O)COC1=C(Cl)C=C(Cl)C=C1
## 94-82-6                   OC(=O)CCCOC1=CC=C(Cl)C=C1Cl
## 90-43-7                     OC1=C(C=CC=C1)C1=CC=CC=C1
## 1007-28-9                       CCNC1=NC(N)=NC(Cl)=N1
## 71751-41-2                                          -
##                                                                                                        All.Compound.Names
## 2971-36-0  2,2-bis(4-hydroxyphenyl)-1,1,1-trichloroethane (hpte)|2,2-bis(4-hydroxyphenyl)-1,1,1-trichloroethane|2971-36-0
## 94-75-7                                                      2,4-d|Dichlorophenoxy|2,4-dichlorophenoxyacetic acid|94-75-7
## 94-82-6                                                                    2,4-db|2,4-dichlorophenoxybutyric acid|94-82-6
## 90-43-7                                                                                            2-phenylphenol|90-43-7
## 1007-28-9                                                            6-desisopropylatrazine|Deisopropylatrazine|1007-28-9
## 71751-41-2                                                                                           Abamectin|71751-41-2
##            logHenry logHenry.Reference logMA logMA.Reference  logP
## 2971-36-0    -7.179                EPA    NA            &lt;NA&gt; 4.622
## 94-75-7      -8.529                EPA    NA            &lt;NA&gt; 2.809
## 94-82-6      -8.833                EPA    NA            &lt;NA&gt; 3.528
## 90-43-7      -7.143                EPA  3.46       Endo 2011 3.091
## 1007-28-9    -8.003                EPA    NA            &lt;NA&gt; 1.150
## 71751-41-2  -15.420           EPISuite    NA            &lt;NA&gt; 4.390
##            logP.Reference logPwa logPwa.Reference logWSol logWSol.Reference
## 2971-36-0             EPA 10.540         EPISuite  -3.707               EPA
## 94-75-7               EPA  5.525         EPISuite  -2.165               EPA
## 94-82-6               EPA  6.685         EPISuite  -3.202               EPA
## 90-43-7               EPA  3.995         EPISuite  -1.812               EPA
## 1007-28-9             EPA  6.953         EPISuite  -2.413               EPA
## 71751-41-2       EPISuite 30.490         EPISuite      NA              &lt;NA&gt;
##                MP MP.Reference    MW MW.Reference pKa_Accept
## 2971-36-0  171.40          EPA 317.6          EPA       None
## 94-75-7    140.60          EPA 221.0          EPA       None
## 94-82-6    118.10          EPA 249.1          EPA       None
## 90-43-7     59.03          EPA 170.2          EPA       None
## 1007-28-9  155.00          EPA 173.6          EPA       1.59
## 71751-41-2 349.80     EPISuite 873.1     EPISuite       None
##            pKa_Accept.Reference         pKa_Donor pKa_Donor.Reference
## 2971-36-0            Sipes 2017        9.63,10.24         Strope 2018
## 94-75-7              Sipes 2017              2.81         Pearce 2017
## 94-82-6              Sipes 2017              3.58         Strope 2018
## 90-43-7              Sipes 2017              9.69         Strope 2018
## 1007-28-9           Strope 201.              None          Sipes 2017
## 71751-41-2           Sipes 2017 12.47,13.17,13.80         Strope 2018
##            All.Species DTXSID.Reference Formula.Reference Human.Clint
## 2971-36-0        Human              EPA               EPA       136.5
## 94-75-7      Human|Rat              EPA               EPA           0
## 94-82-6          Human              EPA               EPA           0
## 90-43-7          Human              EPA               EPA        2.08
## 1007-28-9        Human              EPA               EPA           0
## 71751-41-2       Human              EPA               EPA        5.24
##            Human.Clint.pValue Human.Clint.pValue.Reference
## 2971-36-0            3.57e-05                 Wetmore 2012
## 94-75-7              1.49e-01                 Wetmore 2012
## 94-82-6              1.04e-01                 Wetmore 2012
## 90-43-7              1.64e-01                 Wetmore 2012
## 1007-28-9            5.39e-01                 Wetmore 2012
## 71751-41-2           9.17e-04                 Wetmore 2012
##            Human.Clint.Reference Human.Fgutabs Human.Fgutabs.Reference
## 2971-36-0           Wetmore 2012            NA                    &lt;NA&gt;
## 94-75-7             Wetmore 2012            NA                    &lt;NA&gt;
## 94-82-6             Wetmore 2012            NA                    &lt;NA&gt;
## 90-43-7             Wetmore 2012            NA                    &lt;NA&gt;
## 1007-28-9           Wetmore 2012            NA                    &lt;NA&gt;
## 71751-41-2          Wetmore 2012            NA                    &lt;NA&gt;
##            Human.Funbound.plasma Human.Funbound.plasma.Reference
## 2971-36-0                  0.000                    Wetmore 2012
## 94-75-7                    0.040                    Wetmore 2012
## 94-82-6                    0.007                    Wetmore 2012
## 90-43-7                    0.041                    Wetmore 2012
## 1007-28-9                  0.459                    Wetmore 2012
## 71751-41-2                 0.067                    Wetmore 2012
##            Human.Rblood2plasma Human.Rblood2plasma.Reference
## 2971-36-0                   NA                          &lt;NA&gt;
## 94-75-7                   2.11                           TNO
## 94-82-6                     NA                          &lt;NA&gt;
## 90-43-7                     NA                          &lt;NA&gt;
## 1007-28-9                   NA                          &lt;NA&gt;
## 71751-41-2                  NA                          &lt;NA&gt;
##            Mouse.Funbound.plasma Mouse.Funbound.plasma.Reference
## 2971-36-0                   &lt;NA&gt;                            &lt;NA&gt;
## 94-75-7                     &lt;NA&gt;                            &lt;NA&gt;
## 94-82-6                     &lt;NA&gt;                            &lt;NA&gt;
## 90-43-7                     &lt;NA&gt;                            &lt;NA&gt;
## 1007-28-9                   &lt;NA&gt;                            &lt;NA&gt;
## 71751-41-2                  &lt;NA&gt;                            &lt;NA&gt;
##            Rabbit.Funbound.plasma Rabbit.Funbound.plasma.Reference Rat.Clint
## 2971-36-0                    &lt;NA&gt;                             &lt;NA&gt;      &lt;NA&gt;
## 94-75-7                      &lt;NA&gt;                             &lt;NA&gt;         0
## 94-82-6                      &lt;NA&gt;                             &lt;NA&gt;      &lt;NA&gt;
## 90-43-7                      &lt;NA&gt;                             &lt;NA&gt;      &lt;NA&gt;
## 1007-28-9                    &lt;NA&gt;                             &lt;NA&gt;      &lt;NA&gt;
## 71751-41-2                   &lt;NA&gt;                             &lt;NA&gt;      &lt;NA&gt;
##            Rat.Clint.pValue Rat.Clint.pValue.Reference Rat.Clint.Reference
## 2971-36-0                NA                       &lt;NA&gt;                &lt;NA&gt;
## 94-75-7               0.137               Wetmore 2013        Wetmore 2013
## 94-82-6                  NA                       &lt;NA&gt;                &lt;NA&gt;
## 90-43-7                  NA                       &lt;NA&gt;                &lt;NA&gt;
## 1007-28-9                NA                       &lt;NA&gt;                &lt;NA&gt;
## 71751-41-2               NA                       &lt;NA&gt;                &lt;NA&gt;
##            Rat.Fgutabs Rat.Fgutabs.Reference Rat.Funbound.plasma
## 2971-36-0           NA                  &lt;NA&gt;                &lt;NA&gt;
## 94-75-7             NA                  &lt;NA&gt;             0.02976
## 94-82-6             NA                  &lt;NA&gt;                &lt;NA&gt;
## 90-43-7             NA                  &lt;NA&gt;                &lt;NA&gt;
## 1007-28-9           NA                  &lt;NA&gt;                &lt;NA&gt;
## 71751-41-2          NA                  &lt;NA&gt;                &lt;NA&gt;
##            Rat.Funbound.plasma.Reference Rat.Rblood2plasma
## 2971-36-0                           &lt;NA&gt;                NA
## 94-75-7                     Wetmore 2013                NA
## 94-82-6                             &lt;NA&gt;                NA
## 90-43-7                             &lt;NA&gt;                NA
## 1007-28-9                           &lt;NA&gt;                NA
## 71751-41-2                          &lt;NA&gt;                NA
##            Rat.Rblood2plasma.Reference SMILES.desalt.Reference Chemical.Class
## 2971-36-0                         &lt;NA&gt;                     EPA               
## 94-75-7                           &lt;NA&gt;                     EPA               
## 94-82-6                           &lt;NA&gt;                     EPA               
## 90-43-7                           &lt;NA&gt;                     EPA               
## 1007-28-9                         &lt;NA&gt;                     EPA               
## 71751-41-2                        &lt;NA&gt;                     EPA</code></pre>
<p>The table contains chemical identifiers: name, CASRN (Chemical Abstract Service Registry Number), and DTXSID (DSSTox ID, a chemical identifier from the EPA Distributed Structure-Searchable Toxicity Database, DSSTox for short – more information can be found at <a href="https://www.epa.gov/chemical-research/distributed-structure-searchable-toxicity-dsstox-database" class="uri">https://www.epa.gov/chemical-research/distributed-structure-searchable-toxicity-dsstox-database</a>). The table also contains physical-chemical properties for each chemical. These are used in predicting tissue partitioning.</p>
<p>The table contains <em>in vitro</em> measured chemical-specific TK parameters, if available. These chemical-specific parameters include intrinsic hepatic clearance (<code>Clint</code>) and fraction unbound to plasma protein (<code>Funbound.plasma</code>) for each chemical. It also contains measured values for oral absorption fraction <code>Fgutabs</code>, and for the partition coefficient between blood and plasma <code>Rblood2plasma</code>, if these values have been measured for a given chemical. If available, there may be chemical-specific TK values for multiple species.</p>
</div>
<div id="listing-chemicals-for-which-a-tk-model-can-be-parameterized" class="section level4">
<h4>Listing chemicals for which a TK model can be parameterized</h4>
<p>You can easily get a list of all the chemicals for which a specific TK model can be parameterized (for a given species, if needed) using the function <code>get_cheminfo()</code>.</p>
<p>For example, here is how you get a list of all the chemicals for which the PBTK model can be parameterized for humans.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="toxicokinetic-modeling.html#cb389-1"></a>chems_pbtk &lt;-<span class="st"> </span><span class="kw">get_cheminfo</span>(<span class="dt">info =</span> <span class="kw">c</span>(<span class="st">&quot;Compound&quot;</span>, <span class="st">&quot;CAS&quot;</span>, <span class="st">&quot;DTXSID&quot;</span>),</span>
<span id="cb389-2"><a href="toxicokinetic-modeling.html#cb389-2"></a>                           <span class="dt">model =</span> <span class="st">&quot;pbtk&quot;</span>,</span>
<span id="cb389-3"><a href="toxicokinetic-modeling.html#cb389-3"></a>                           <span class="dt">species =</span> <span class="st">&quot;Human&quot;</span>)</span>
<span id="cb389-4"><a href="toxicokinetic-modeling.html#cb389-4"></a></span>
<span id="cb389-5"><a href="toxicokinetic-modeling.html#cb389-5"></a><span class="kw">head</span>(chems_pbtk) <span class="co"># First few rows</span></span></code></pre></div>
<pre><code>##                 Compound        CAS        DTXSID
## 1                  2,4-d    94-75-7 DTXSID0020442
## 2                 2,4-db    94-82-6 DTXSID7024035
## 3         2-phenylphenol    90-43-7 DTXSID2021151
## 4 6-desisopropylatrazine  1007-28-9 DTXSID0037495
## 5              Abamectin 71751-41-2 DTXSID8023892
## 6               Acephate 30560-19-1 DTXSID8023846</code></pre>
<p>How many such chemicals have parameter data to run a PBTK model in this package?</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="toxicokinetic-modeling.html#cb391-1"></a><span class="kw">nrow</span>(chems_pbtk)</span></code></pre></div>
<pre><code>## [1] 923</code></pre>
<p>Here is how you get all the chemicals for which the 3-compartment steady-state model can be parameterized for humans.</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="toxicokinetic-modeling.html#cb393-1"></a>chems_3compss &lt;-<span class="st"> </span><span class="kw">get_cheminfo</span>(<span class="dt">info =</span> <span class="kw">c</span>(<span class="st">&quot;Compound&quot;</span>, <span class="st">&quot;CAS&quot;</span>, <span class="st">&quot;DTXSID&quot;</span>),</span>
<span id="cb393-2"><a href="toxicokinetic-modeling.html#cb393-2"></a>                           <span class="dt">model =</span> <span class="st">&quot;3compartmentss&quot;</span>,</span>
<span id="cb393-3"><a href="toxicokinetic-modeling.html#cb393-3"></a>                           <span class="dt">species =</span> <span class="st">&quot;Human&quot;</span>)</span></code></pre></div>
<p>How many such chemicals have parameter data to run a 3-compartment steady-state model in this package?</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="toxicokinetic-modeling.html#cb394-1"></a><span class="kw">nrow</span>(chems_3compss)</span></code></pre></div>
<pre><code>## [1] 998</code></pre>
<p>The 3-compartment steady-state model can be parameterized for a few more chemicals than the PBTK model, because it is a simpler model and requires less data to parameterize. Specifically, the 3-compartment steady-state model does not require estimating tissue partition coefficients, unlike the PBTK model.</p>
</div>
<div id="solving-toxicokinetic-models-to-obtain-internal-chemical-concentration-vs.-time-predictions" class="section level4">
<h4>Solving Toxicokinetic Models to Obtain Internal Chemical Concentration vs. Time Predictions</h4>
<p>You can solve any of the models for a specified chemical and specified dosing protocol, and get concentration vs. time predictions, using the function <code>solve_model()</code>. For example:</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="toxicokinetic-modeling.html#cb396-1"></a>sol_pbtk &lt;-<span class="st"> </span><span class="kw">solve_model</span>(<span class="dt">chem.name =</span> <span class="st">&quot;Bisphenol-A&quot;</span>, <span class="co"># Chemical to simulate</span></span>
<span id="cb396-2"><a href="toxicokinetic-modeling.html#cb396-2"></a>            <span class="dt">model =</span> <span class="st">&quot;pbtk&quot;</span>, <span class="co"># TK model to use</span></span>
<span id="cb396-3"><a href="toxicokinetic-modeling.html#cb396-3"></a>            <span class="dt">dosing =</span> <span class="kw">list</span>(<span class="dt">initial.dose =</span> <span class="ot">NULL</span>, <span class="co"># For repeated dosing, if first dose is different from the rest, specify first dose here</span></span>
<span id="cb396-4"><a href="toxicokinetic-modeling.html#cb396-4"></a>                          <span class="dt">doses.per.day =</span> <span class="dv">1</span>, <span class="co"># Number of doses per day</span></span>
<span id="cb396-5"><a href="toxicokinetic-modeling.html#cb396-5"></a>                          <span class="dt">daily.dose =</span> <span class="dv">1</span>, <span class="co"># Total daily dose in mg/kg units</span></span>
<span id="cb396-6"><a href="toxicokinetic-modeling.html#cb396-6"></a>                          <span class="dt">dosing.matrix =</span> <span class="ot">NULL</span>), <span class="co"># Used to specify more complicated dosing protocols</span></span>
<span id="cb396-7"><a href="toxicokinetic-modeling.html#cb396-7"></a>            <span class="dt">days =</span> <span class="dv">1</span>) <span class="co"># Number of days to simulate</span></span></code></pre></div>
<pre><code>## Human amounts returned in umol and concentration returned in uM units.
## AUC is area under plasma concentration in uM * days units with 
## Rblood2plasma = 0.79.</code></pre>
<p>There are some cryptic-sounding warnings that can safely be ignored. (They are providing information about certain assumptions that were made while solving the model). Then there is a final message providing the units of the output.</p>
<p>The output, assigned to <code>sol_pbtk</code>, is a matrix with concentration vs. time data for each of the compartments in the <code>pbtk</code> model. Time is in units of days. Additionally, the output traces the amount excreted via passive renal filtration (<code>Atubules</code>), the amount metabolized in the liver (<code>Ametabolized</code>), and the cumulative area under the curve for plasma concentration vs. time (<code>AUC</code>). Here are the first few rows of <code>sol_pbtk</code> so you can see the format.</p>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="toxicokinetic-modeling.html#cb398-1"></a><span class="kw">head</span>(sol_pbtk)</span></code></pre></div>
<pre><code>##         time Agutlumen    Cgut    Cliver      Cven Clung   Cart   Crest Ckidney
## [1,] 0.00000      0.00  0.0000 0.000e+00 0.000e+00 0.000 0.0000 0.00000   0.000
## [2,] 0.00001    306.50  0.1449 4.361e-05 5.000e-09 0.000 0.0000 0.00000   0.000
## [3,] 0.01042    177.80 72.3500 2.371e+01 2.840e-01 2.350 0.2472 0.06483   3.119
## [4,] 0.02083    103.10 73.6200 4.914e+01 6.823e-01 5.985 0.6532 0.40620  12.430
## [5,] 0.03125     59.78 59.9200 5.925e+01 9.131e-01 8.155 0.8999 0.95900  19.990
## [6,] 0.04167     34.66 46.1500 5.834e+01 9.873e-01 8.886 0.9852 1.56800  23.520
##        Cplasma Atubules Ametabolized      AUC
## [1,] 0.000e+00 0.000000    0.000e+00 0.000000
## [2,] 6.000e-09 0.000000    2.000e-09 0.000000
## [3,] 3.595e-01 0.001953    1.099e+00 0.001388
## [4,] 8.637e-01 0.019830    5.474e+00 0.007886
## [5,] 1.156e+00 0.058500    1.191e+01 0.018610
## [6,] 1.250e+00 0.110100    1.883e+01 0.031270</code></pre>
<p>You can plot the results, for example plasma concentration vs. time.</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="toxicokinetic-modeling.html#cb400-1"></a>sol_pbtk &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(sol_pbtk) <span class="co"># Because ggplot2 requires data.frame input, not matrix</span></span>
<span id="cb400-2"><a href="toxicokinetic-modeling.html#cb400-2"></a></span>
<span id="cb400-3"><a href="toxicokinetic-modeling.html#cb400-3"></a><span class="kw">ggplot</span>(sol_pbtk) <span class="op">+</span></span>
<span id="cb400-4"><a href="toxicokinetic-modeling.html#cb400-4"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> time,</span>
<span id="cb400-5"><a href="toxicokinetic-modeling.html#cb400-5"></a>                <span class="dt">y =</span> Cplasma)) <span class="op">+</span></span>
<span id="cb400-6"><a href="toxicokinetic-modeling.html#cb400-6"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb400-7"><a href="toxicokinetic-modeling.html#cb400-7"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Time, days&quot;</span>) <span class="op">+</span></span>
<span id="cb400-8"><a href="toxicokinetic-modeling.html#cb400-8"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Cplasma, uM&quot;</span>) <span class="op">+</span></span>
<span id="cb400-9"><a href="toxicokinetic-modeling.html#cb400-9"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&quot;Plasma concentration vs. time for single dose 1 mg/kg Bisphenol-A&quot;</span>)</span></code></pre></div>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-157-1.png" width="576" /></p>
</div>
<div id="calculating-summary-metrics-of-internal-dose-produced-from-tk-models" class="section level4">
<h4>Calculating summary metrics of internal dose produced from TK models</h4>
<p>We can calculate summary metrics of internal dose – peak concentration, average concentration, and AUC – using the function <code>calc_tkstats()</code>. We have to specify the dosing protocol and length of simulation. Here, we use the same dosing protocol and simulation length as in the plot above.</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="toxicokinetic-modeling.html#cb401-1"></a>tkstats &lt;-<span class="st"> </span><span class="kw">calc_tkstats</span>(<span class="dt">chem.name =</span> <span class="st">&quot;Bisphenol-A&quot;</span>, <span class="co"># Chemical to simulate</span></span>
<span id="cb401-2"><a href="toxicokinetic-modeling.html#cb401-2"></a>             <span class="dt">stats =</span> <span class="kw">c</span>(<span class="st">&quot;AUC&quot;</span>, <span class="st">&quot;peak&quot;</span>, <span class="st">&quot;mean&quot;</span>), <span class="co"># Which metrics to return (these are the only three choices)</span></span>
<span id="cb401-3"><a href="toxicokinetic-modeling.html#cb401-3"></a>             <span class="dt">model =</span> <span class="st">&quot;pbtk&quot;</span>, <span class="co"># Model to use</span></span>
<span id="cb401-4"><a href="toxicokinetic-modeling.html#cb401-4"></a>             <span class="dt">tissue =</span> <span class="st">&quot;plasma&quot;</span>, <span class="co"># Tissue for which to return internal dose metrics</span></span>
<span id="cb401-5"><a href="toxicokinetic-modeling.html#cb401-5"></a>             <span class="dt">days =</span> <span class="dv">1</span>, <span class="co"># Length of simulation</span></span>
<span id="cb401-6"><a href="toxicokinetic-modeling.html#cb401-6"></a>             <span class="dt">daily.dose =</span> <span class="dv">1</span>, <span class="co"># Total daily dose in mg/kg/day</span></span>
<span id="cb401-7"><a href="toxicokinetic-modeling.html#cb401-7"></a>             <span class="dt">doses.per.day =</span> <span class="dv">1</span>) <span class="co"># Number of doses per day</span></span></code></pre></div>
<pre><code>## Human plasma concentrations returned in uM units.
## AUC is area under plasma concentration curve in uM * days units with Rblood2plasma = 0.79 .</code></pre>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="toxicokinetic-modeling.html#cb403-1"></a><span class="kw">print</span>(tkstats)</span></code></pre></div>
<pre><code>## $AUC
## [1] 0.6265
## 
## $peak
## [1] 1.25
## 
## $mean
## [1] 0.6265</code></pre>
<p><br></p>
<div class="question">
<p><i>With this, we can answer <strong>Environmental Health Question 2</strong>:</i>
After solving the TK model that evaluates bisphenol-A, what is the maximum concentration of bisphenol-A estimated to occur in human plasma, after 1 exposure dose of 1 mg/kg/day?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: The peak plasma concentration estimate for bisphenol-A, under the conditions tested, is 1.25 uM.</p>
</div>
<p><br></p>
</div>
</div>
<div id="calculating-steady-state-concentration" class="section level2">
<h2>Calculating steady-state concentration</h2>
<p>Another summary metric is the steady-state concentration: If the same dose is given repeatedly over many days, the body concentration will (usually) reach a steady state after some time. The value of this steady-state concentration, and the time needed to achieve steady state, are different for different chemicals. Steady-state concentrations are useful when considering long-term, low=level exposures, which is frequently the situation in environmental health.</p>
<p>For example, here is a plot of plasma concentration vs. time for 1 mg/kg/day Bisphenol-A, administered for 12 days. You can see how the average plasma concentration reaches a steady state around 1.5 uM. Each peak represents one day’s dose.</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="toxicokinetic-modeling.html#cb405-1"></a>foo &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">solve_pbtk</span>(</span>
<span id="cb405-2"><a href="toxicokinetic-modeling.html#cb405-2"></a>    <span class="dt">chem.name=</span><span class="st">&#39;Bisphenol-A&#39;</span>,</span>
<span id="cb405-3"><a href="toxicokinetic-modeling.html#cb405-3"></a>    <span class="dt">daily.dose=</span><span class="dv">1</span>,</span>
<span id="cb405-4"><a href="toxicokinetic-modeling.html#cb405-4"></a>    <span class="dt">days=</span><span class="dv">12</span>,</span>
<span id="cb405-5"><a href="toxicokinetic-modeling.html#cb405-5"></a>    <span class="dt">doses.per.day=</span><span class="dv">1</span>,</span>
<span id="cb405-6"><a href="toxicokinetic-modeling.html#cb405-6"></a>    <span class="dt">tsteps=</span><span class="dv">2</span>))</span></code></pre></div>
<pre><code>## Human amounts returned in umol and concentration returned in uM units.
## AUC is area under plasma concentration in uM * days units with 
## Rblood2plasma = 0.79.</code></pre>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="toxicokinetic-modeling.html#cb407-1"></a><span class="kw">ggplot</span>(foo) <span class="op">+</span></span>
<span id="cb407-2"><a href="toxicokinetic-modeling.html#cb407-2"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> time,</span>
<span id="cb407-3"><a href="toxicokinetic-modeling.html#cb407-3"></a>                <span class="dt">y=</span> Cplasma)) <span class="op">+</span></span>
<span id="cb407-4"><a href="toxicokinetic-modeling.html#cb407-4"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dv">0</span>,<span class="dv">12</span>)) <span class="op">+</span></span>
<span id="cb407-5"><a href="toxicokinetic-modeling.html#cb407-5"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Time, days&quot;</span>) <span class="op">+</span></span>
<span id="cb407-6"><a href="toxicokinetic-modeling.html#cb407-6"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Cplasma, uM&quot;</span>)</span></code></pre></div>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-159-1.png" width="576" /></p>
<p><code>httk</code> includes a function <code>calc_analytic_css()</code> to calculate the steady-state plasma concentration (<span class="math inline">\(C_{ss}\)</span> for short) analytically for each model, for a specified chemical and daily oral dose. This function assumes that the daily oral dose is administered as an oral infusion, rather than a single oral bolus dose – in effect, that the daily dose is divided into many small doses over the day. Therefore, the result of <code>calc_analytic_css()</code> may be slightly different than our previous estimate based on the concentration vs. time plot from a single oral bolus dose every day.</p>
<p>Here is the result of <code>calc_analytic_css()</code> for a 1 mg/kg/day dose of bisphenol-A.</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="toxicokinetic-modeling.html#cb408-1"></a><span class="kw">calc_analytic_css</span>(<span class="dt">chem.name =</span> <span class="st">&quot;Bisphenol-A&quot;</span>,</span>
<span id="cb408-2"><a href="toxicokinetic-modeling.html#cb408-2"></a>                  <span class="dt">daily.dose =</span> <span class="dv">1</span>,</span>
<span id="cb408-3"><a href="toxicokinetic-modeling.html#cb408-3"></a>                  <span class="dt">output.units =</span> <span class="st">&quot;uM&quot;</span>,</span>
<span id="cb408-4"><a href="toxicokinetic-modeling.html#cb408-4"></a>                  <span class="dt">model =</span> <span class="st">&quot;pbtk&quot;</span>,</span>
<span id="cb408-5"><a href="toxicokinetic-modeling.html#cb408-5"></a>                  <span class="dt">concentration =</span> <span class="st">&quot;plasma&quot;</span>)</span></code></pre></div>
<pre><code>## Plasma concentration returned in uM units.</code></pre>
<pre><code>## [1] 1.156</code></pre>
<p><br></p>
<div class="question">
<p><i>With this, we can answer <strong>Environmental Health Question 2</strong>:</i>
After solving the TK model that evaluates bisphenol-A, what is the steady-state concentration of bisphenol-A estimated to occur in human plasma, for a long-term oral infusion dose of 1 mg/kg/day?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: The steady-state plasma concentration estimate for bisphenol-A, under the conditions tested, is 1.156 uM.</p>
</div>
<p><br></p>
<div id="steady-state-concentration-is-linear-with-dose-for-httk-models" class="section level4">
<h4>Steady-state concentration is linear with dose for <code>httk</code> models</h4>
<p>For the TK models included in the <code>httk</code> package, steady-state concentration is linear with dose for a given chemical. The slope of the line is simply the steady-state concentration for a dose of 1 mg/kg/day. This can be shown by solving <code>calc_analytic_css()</code> for several doses, and plotting the dose-<span class="math inline">\(C_{ss}\)</span> points along a line whose slope is equal to <span class="math inline">\(C_{ss}\)</span> for 1 mg/kg/day.</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="toxicokinetic-modeling.html#cb411-1"></a><span class="co"># Choose five doses at which to find the Css</span></span>
<span id="cb411-2"><a href="toxicokinetic-modeling.html#cb411-2"></a>doses &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.1</span>, <span class="co"># Qll mg/kg/day</span></span>
<span id="cb411-3"><a href="toxicokinetic-modeling.html#cb411-3"></a>           <span class="fl">0.5</span>,</span>
<span id="cb411-4"><a href="toxicokinetic-modeling.html#cb411-4"></a>           <span class="fl">1.0</span>,</span>
<span id="cb411-5"><a href="toxicokinetic-modeling.html#cb411-5"></a>           <span class="fl">1.5</span>,</span>
<span id="cb411-6"><a href="toxicokinetic-modeling.html#cb411-6"></a>           <span class="fl">2.0</span>)</span>
<span id="cb411-7"><a href="toxicokinetic-modeling.html#cb411-7"></a><span class="kw">suppressWarnings</span>(bpa_css &lt;-<span class="st"> </span><span class="kw">sapply</span>(doses,</span>
<span id="cb411-8"><a href="toxicokinetic-modeling.html#cb411-8"></a>                  <span class="cf">function</span>(dose) <span class="kw">calc_analytic_css</span>(<span class="dt">chem.name =</span> <span class="st">&quot;Bisphenol-A&quot;</span>,</span>
<span id="cb411-9"><a href="toxicokinetic-modeling.html#cb411-9"></a>                  <span class="dt">daily.dose =</span> dose,</span>
<span id="cb411-10"><a href="toxicokinetic-modeling.html#cb411-10"></a>                  <span class="dt">output.units =</span> <span class="st">&quot;uM&quot;</span>,</span>
<span id="cb411-11"><a href="toxicokinetic-modeling.html#cb411-11"></a>                  <span class="dt">model =</span> <span class="st">&quot;pbtk&quot;</span>,</span>
<span id="cb411-12"><a href="toxicokinetic-modeling.html#cb411-12"></a>                  <span class="dt">concentration =</span> <span class="st">&quot;plasma&quot;</span>,</span>
<span id="cb411-13"><a href="toxicokinetic-modeling.html#cb411-13"></a>                  <span class="dt">suppress.messages =</span> <span class="ot">TRUE</span>)))</span>
<span id="cb411-14"><a href="toxicokinetic-modeling.html#cb411-14"></a></span>
<span id="cb411-15"><a href="toxicokinetic-modeling.html#cb411-15"></a>DF &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">dose =</span> doses,</span>
<span id="cb411-16"><a href="toxicokinetic-modeling.html#cb411-16"></a>                 <span class="dt">Css =</span> bpa_css)</span>
<span id="cb411-17"><a href="toxicokinetic-modeling.html#cb411-17"></a></span>
<span id="cb411-18"><a href="toxicokinetic-modeling.html#cb411-18"></a><span class="co">#Plot the results</span></span>
<span id="cb411-19"><a href="toxicokinetic-modeling.html#cb411-19"></a>Cssdosefig  &lt;-<span class="st"> </span><span class="kw">ggplot</span>(DF) <span class="op">+</span></span>
<span id="cb411-20"><a href="toxicokinetic-modeling.html#cb411-20"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> dose,</span>
<span id="cb411-21"><a href="toxicokinetic-modeling.html#cb411-21"></a>                 <span class="dt">y =</span> Css),</span>
<span id="cb411-22"><a href="toxicokinetic-modeling.html#cb411-22"></a>             <span class="dt">size =</span> <span class="dv">3</span>) <span class="op">+</span></span>
<span id="cb411-23"><a href="toxicokinetic-modeling.html#cb411-23"></a><span class="st">  </span><span class="kw">geom_abline</span>( <span class="co"># Plot a straight line</span></span>
<span id="cb411-24"><a href="toxicokinetic-modeling.html#cb411-24"></a>    <span class="dt">intercept =</span> <span class="dv">0</span>, <span class="co">#intercept 0</span></span>
<span id="cb411-25"><a href="toxicokinetic-modeling.html#cb411-25"></a>              <span class="dt">slope =</span> DF[DF<span class="op">$</span>dose<span class="op">==</span><span class="dv">1</span>, <span class="co"># Slope = Css for 1 mg/kg/day</span></span>
<span id="cb411-26"><a href="toxicokinetic-modeling.html#cb411-26"></a>                         <span class="st">&quot;Css&quot;</span>],</span>
<span id="cb411-27"><a href="toxicokinetic-modeling.html#cb411-27"></a>    <span class="dt">linetype =</span> <span class="dv">2</span></span>
<span id="cb411-28"><a href="toxicokinetic-modeling.html#cb411-28"></a>    ) <span class="op">+</span></span>
<span id="cb411-29"><a href="toxicokinetic-modeling.html#cb411-29"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Daily dose, mg/kg/day&quot;</span>) <span class="op">+</span></span>
<span id="cb411-30"><a href="toxicokinetic-modeling.html#cb411-30"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Css, uM&quot;</span>)</span>
<span id="cb411-31"><a href="toxicokinetic-modeling.html#cb411-31"></a></span>
<span id="cb411-32"><a href="toxicokinetic-modeling.html#cb411-32"></a><span class="kw">print</span>(Cssdosefig)</span></code></pre></div>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-161-1.png" width="576" /></p>
</div>
</div>
<div id="reverse-toxicokinetics" class="section level2">
<h2>Reverse Toxicokinetics</h2>
<p>In the previous TK examples, we started with a specified dosing protocol, then solved the TK models to find the resulting concentration in the body (e.g., in plasma). This allows us to convert from external exposure metrics to internal exposure metrics. However, many environmental health questions require the reverse: converting from internal exposure metrics to external exposure metrics.</p>
<p>For example, when health effects of environmental chemicals are studied in epidemiological cohorts, adverse health effects are often related to <em>internal</em> exposure metrics, such as blood or plasma concentration of a chemical. Similarly, <em>in vitro</em> studies of chemical bioactivity (for example, the ToxCast program) relate bioactivity to <em>in vitro</em> concentration, which can be consdered analogous to internal exposure or body concentration. So we may know the <em>internal</em> exposure level associated with some adverse health effect of a chemical.</p>
<p>However, risk assessors and risk managers typically control <em>external</em> exposure to reduce the risk of adverse health effects. They need some way to start from an internal exposure associated with adverse health effects, and convert to the corresponding external exposure.</p>
<p>The solution is <em>reverse toxicokinetics</em> (reverse TK). Starting with a specified internal exposure metric (body concentration), solve the TK model <em>in reverse</em> to find the corresponding external exposure that produced that concentration.</p>
<p>When exposures are long-term and low-level (as environmental exposures often are), then the relevant internal exposure metric is the steady-state concentration. In this case, it is useful to remember the linear relationship between <span class="math inline">\(C_{ss}\)</span> and dose for the <code>httk</code> TK models. It gives you a quick and easy way to perform reverse TK for the steady-state case.</p>
<p>The procedure is illustrated graphically below.</p>
<ol style="list-style-type: decimal">
<li>Begin with a “target” concentration on the y-axis (labeled <span class="math inline">\(C_{\textrm{target}}\)</span>). For example, <span class="math inline">\(C_{\textrm{target}}\)</span> may be the <em>in vitro</em> concentration associated with bioactivity in a ToxCast assay, or the plasma concentration associated with an adverse health effect in an epidemiological study.</li>
<li>Draw a horizontal line over to the <span class="math inline">\(C_{ss}\)</span>-dose line.</li>
<li>Drop down vertically to the x-axis and read off the corresponding dose. This is the <em>administered equivalent dose</em> (AED): the the external dose or exposure rate, in mg/kg/day, that would produce an internal steady-state plasma concentration equal to the target concentration.</li>
</ol>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-162-1.png" width="576" /></p>
<p>Mathematically, the relation is very simple:</p>
<p><span class="math display">\[ AED = \frac{C_{\textrm{target}}}{C_{ss}\textrm{-dose slope}} \]</span></p>
<p>Since the <span class="math inline">\(C_{ss}\)</span>-dose slope is simply <span class="math inline">\(C_{ss}\)</span> for a daily dose of 1 mg/kg/day, this equation can be rewritten as</p>
<p><span class="math display">\[ AED = \frac{C_{\textrm{target}}}{C_{ss}\textrm{ for 1 mg/kg/day}} \]</span></p>
<div id="capturing-population-variability-and-uncertainty" class="section level4">
<h4>Capturing Population Variability and Uncertainty</h4>
<p>For a given dose, <span class="math inline">\(C_{ss}\)</span> is determined by the values of the parameters of the TK model. These parameters describe absorption, distribution, metabolism, and excretion (ADME) of each chemical. They include both chemical-specific parameters, describing hepatic clearance and protein binding, and chemical-independent parameters, describing physiology. A table of these parameters is presented below.</p>
<table>
<colgroup>
<col width="21%" />
<col width="38%" />
<col width="27%" />
<col width="12%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Parameter</th>
<th align="left">Details</th>
<th align="left">Estimated</th>
<th align="left">Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Intrinsic hepatic clearance rate</td>
<td align="left">Rate at which liver removes chemical from blood</td>
<td align="left">Measured <em>in vitro</em></td>
<td align="left">Chemical-specific</td>
</tr>
<tr class="even">
<td align="left">Fraction unbound to plasma protein</td>
<td align="left">Free fraction of chemical in plasma</td>
<td align="left">Measured <em>in vitro</em></td>
<td align="left">Chemical-specific</td>
</tr>
<tr class="odd">
<td align="left">Tissue:plasma partition coefficients</td>
<td align="left">Ratio of concentration in body tissues to concentration in plasma</td>
<td align="left">Estimated from chemical and tissue properties</td>
<td align="left">Chemical-specific</td>
</tr>
<tr class="even">
<td align="left">Tissue masses</td>
<td align="left">Mass of each body tissue (including total body weight)</td>
<td align="left">From anatomical literature</td>
<td align="left">Chemical-independent</td>
</tr>
<tr class="odd">
<td align="left">Tissue blood flows</td>
<td align="left">Blood flow rate to each body tissue</td>
<td align="left">From anatomical literature</td>
<td align="left">Chemical-independent</td>
</tr>
<tr class="even">
<td align="left">Glomerular filtration rate</td>
<td align="left">Rate at which kidneys remove chemical from blood</td>
<td align="left">From anatomical literature</td>
<td align="left">Chemical-independent</td>
</tr>
<tr class="odd">
<td align="left">Hepatocellularity</td>
<td align="left">Number of cells per mg liver</td>
<td align="left">From anatomical literature</td>
<td align="left">Chemical-independent</td>
</tr>
</tbody>
</table>
<p>Because these parameters represent physiology and chemical-body interactions, their exact values will vary across individuals in a population, reflecting population physiological variability. Additionally, parameters are subject to measurement uncertainty.</p>
<p>Since the <span class="math inline">\(C_{ss}\)</span>-dose relation is determined by these parameters, variability and uncertainty in the TK parameters translates directly into variability and uncertainty in <span class="math inline">\(C_{ss}\)</span> for a given dose. In other words, there is a distribution of <span class="math inline">\(C_{ss}\)</span> values for each daily dose level of a chemical.</p>
<p>The <span class="math inline">\(C_{ss}\)</span>-dose relationship is still linear when variability and uncertainty are taken into account. However, rather than a single <span class="math inline">\(C_{ss}\)</span>-dose slope, there is a distribution of <span class="math inline">\(C_{ss}\)</span>-dose slopes. Because the <span class="math inline">\(C_{ss}\)</span>-dose slope is simply the <span class="math inline">\(C_{ss}\)</span> value for an exposure rate of 1 mg/kg/day, the distribution of the <span class="math inline">\(C_{ss}\)</span>-dose slope is the same as the <span class="math inline">\(C_{ss}\)</span> distribution for an exposure rate of 1 mg/kg/day.</p>
<p>A distribution of <span class="math inline">\(C_{ss}\)</span>-dose slopes is illustrated in the figure below, along with boxplots illustrating the distributions for <span class="math inline">\(C_{ss}\)</span> itself at five different dose levels: 0.05, 0.25, 0.5, 0.75, and 0.95 mg/kg/day.</p>
<div class="figure"><span id="fig:unnamed-chunk-164"></span>
<img src="02-Chapter2_files/figure-html/unnamed-chunk-164-1.png" alt="Boxplots: Distributions of Css for five daily dose levels of Bisphenol-A. Boxes extend from 25th to 75th percentile. Lower whisker = 5th percentile; upper whisker = 95th percentile. Lines: Css-dose relations for each quantile." width="576" />
<p class="caption">
Figure 1: Boxplots: Distributions of Css for five daily dose levels of Bisphenol-A. Boxes extend from 25th to 75th percentile. Lower whisker = 5th percentile; upper whisker = 95th percentile. Lines: Css-dose relations for each quantile.
</p>
</div>
</div>
<div id="variability-and-uncertainty-in-reverse-toxicokinetics" class="section level4">
<h4>Variability and Uncertainty in Reverse Toxicokinetics</h4>
<p>Earlier, we found that with a linear <span class="math inline">\(C_{ss}\)</span>-dose relation, reverse toxicokinetics became a matter of a simple linear equation. For a given target concentration – for example, a plasma concentration associated with adverse health effects <em>in vivo</em>, or a concentration associated with bioactivity <em>in vitro</em> – we could predict an AED (administered equivalent dose), the external exposure rate in mg/kg/day that would produce the target concentration at steady state.</p>
<p><span class="math display">\[ AED = \frac{C_{\textrm{target}}}{C_{ss}\textrm{-dose slope}} \]</span></p>
<p>Since AED depends on the <span class="math inline">\(C_{ss}\)</span>-dose slope, variability and uncertainty in that slope will induce variability and uncertainty in the AED. A distribution of slopes will lead to a distribution of AEDs for the same target concentration.</p>
<p>For example, a graphical representation of finding the AED distribution for a target concentration of 1 uM looks like this, for the same arbitrary example chemical used to illustrate the distribution of <span class="math inline">\(C_{ss}\)</span>-dose slopes above. (The lines shown in this plot are the same as the previous plot, but the plot has been “zoomed in” on the y-axis.)</p>
<p>The steps are the same as before:</p>
<ol style="list-style-type: decimal">
<li>Begin with a “target” concentration on the y-axis, here 1 uM.</li>
<li>Draw a horizontal line over to intersect each <span class="math inline">\(C_{ss}\)</span>-dose line.</li>
<li>Where the horizontal line intersects each <span class="math inline">\(C_{ss}\)</span>-dose line, drop down vertically to the x-axis and read off each corresponding AED (marked with colored circles matching the color of each <span class="math inline">\(C_{ss}\)</span>-dose line).</li>
</ol>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-165-1.png" width="576" /></p>
<p>Notice that the line with the steepest, 95th-percentile slope (the purple line) yields the lowest AED (the purple dot, approximately 0.07 mg/kg/day for this example chemical), and the line with the shallowest, 5th-percentile slope (the turquoise blue line) yields the highest AED (the turquoise dot, approximately 2 mg/kg/day for this example chemical).</p>
<p>In general, the 95th-percentile <span class="math inline">\(C_{ss}\)</span>-dose slope represents the most-sensitive 5% of the population – individuals who will reach the target concentration in their body with the smallest daily doses. Therefore, using the AED for the 95th-percentile <span class="math inline">\(C_{ss}\)</span>-dose slope is a conservative choice, health-protective for 95% of the estimated population.</p>
</div>
</div>
<div id="monte-carlo-approach" class="section level2">
<h2>Monte Carlo Approach</h2>
<p>The <code>httk</code> package implements a Monte Carlo approach for simulating variability and uncertainty in TK.</p>
<p><code>httk</code> first defines distributions for the TK model parameters, representing population variabilty. These distributions are defined based on real data about U.S. population demographics and physiology collected as part of the Centers for Disease Control’s National Health and Nutrition Examination Survey (NHANES) <a href="https://pubmed.ncbi.nlm.nih.gov/28628784/">(Ring et al., 2017)</a>. TK parameters with known measurement uncertainty (intrinsic hepatic clearance rate and fraction of chemical unbound in plasma) additionally have distributions defined to represent their uncertainty <a href="https://pubmed.ncbi.nlm.nih.gov/31532498/">(Wambaugh et al., 2019)</a>.</p>
<p>Then, <code>httk</code> samples sets of TK parameter values from these distributions (including appropriate correlations: for example, liver mass is correlated with body weight). Each sampled set of TK parameter values represents one “simulated individual.”</p>
<p>Next, <code>httk</code> calculates the <span class="math inline">\(C_{ss}\)</span>-dose slope for each “simulated individual.” The resulting sample of <span class="math inline">\(C_{ss}\)</span>-dose slopes can be used to characterize the distribution of <span class="math inline">\(C_{ss}\)</span>-dose slopes – for example, by calculating percentiles.</p>
<p><code>httk</code> makes this whole Monte Carlo process simple and transparent for the user, You just need to call one function, <code>calc_mc_css()</code>, specifying the chemical whose <span class="math inline">\(C_{ss}\)</span>-dose slope distribution you want to calculate. Behind the scenes, <code>httk</code> will perform all the Monte Carlo calculations. It will return percentiles of the <span class="math inline">\(C_{ss}\)</span>-dose slope (by default), or it can return all individual samples of <span class="math inline">\(C_{ss}\)</span>-dose slope (if you want to do some calculations of your own).</p>
</div>
<div id="chemical-specific-example" class="section level2">
<h2>Chemical-Specific Example</h2>
<p>Here is an example of capturing population variability for bisphenol-A plasma concentration estimates. The following code estimates the 5th percentile, 50th percentile, and 95th percentile of the <span class="math inline">\(C_{ss}\)</span>-dose slope for the chemical bisphenol-A. For the sake of simplicity, we will use the 3-compartment steady-state model (rather than the PBTK model used in the previous examples).</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="toxicokinetic-modeling.html#cb412-1"></a>css_examp &lt;-<span class="st"> </span><span class="kw">calc_mc_css</span>(<span class="dt">chem.name =</span> <span class="st">&quot;Bisphenol-A&quot;</span>,</span>
<span id="cb412-2"><a href="toxicokinetic-modeling.html#cb412-2"></a>            <span class="dt">which.quantile =</span> <span class="kw">c</span>(<span class="fl">0.05</span>, <span class="co"># Specify which quantiles to return</span></span>
<span id="cb412-3"><a href="toxicokinetic-modeling.html#cb412-3"></a>                               <span class="fl">0.5</span>,</span>
<span id="cb412-4"><a href="toxicokinetic-modeling.html#cb412-4"></a>                               <span class="fl">0.95</span>),</span>
<span id="cb412-5"><a href="toxicokinetic-modeling.html#cb412-5"></a>            <span class="dt">model =</span> <span class="st">&quot;3compartmentss&quot;</span>, <span class="co"># Which model to use to calculate Css</span></span>
<span id="cb412-6"><a href="toxicokinetic-modeling.html#cb412-6"></a>            <span class="dt">output.units =</span> <span class="st">&quot;uM&quot;</span>) <span class="co"># Could also choose mg/Lo</span></span></code></pre></div>
<pre><code>## Human plasma concentration returned in uM units for 0.05 0.5 0.95 quantile.</code></pre>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="toxicokinetic-modeling.html#cb414-1"></a><span class="kw">print</span>(css_examp)</span></code></pre></div>
<pre><code>##      5%     50%     95% 
##  0.4948  1.9080 13.4800</code></pre>
<p>Recall that the <span class="math inline">\(C_{ss}\)</span>-dose slope is the same as <span class="math inline">\(C_{ss}\)</span> for a daily dose of 1 mg/kg/day. The function <code>calc_mc_css()</code> therefore assumes a dose of 1 mg/kg/day and calculates the resulting <span class="math inline">\(C_{ss}\)</span> distribution. If you need to calculate the <span class="math inline">\(C_{ss}\)</span> distribution for a different dose, e.g. 2 mg/kg/day, you can simply multiply the <span class="math inline">\(C_{ss}\)</span> percentiles from <code>calc_mc_css()</code> by your desired dose.</p>
<p>The steady-state plasma concentration for 1 mg/kg/day dose is returned in units of uM. The three requested quantiles are returned as a named numeric vector (whose names in this case are <code>5%</code>, <code>50%</code>, and <code>95%</code>).</p>
<p><br></p>
<div class="question">
<p><i>With this, we can answer <strong>Environmental Health Question 3</strong>:</i>
What is the predicted range of bisphenol-A concentrations in plasma that can occur in a human population, assuming a long-term exposure rate of 1 mg/kg/day and steady-state conditions? Provide estimates at the 5th, 50th, and 95th percentile?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: For a human population exposed to 1 mg/kg/day bisphenol-A, plasma concentrations are estimated to be 0.5125 uM at the 5th percentile, 2.07 uM at the 50th percentile, and 14.2 uM at the 95th percentile.</p>
</div>
<p><br></p>
<div id="high-throughput-example-capturing-population-variability-for-1000-chemicals" class="section level4">
<h4>High-Throughput Example Capturing Population Variability for ~1000 Chemicals</h4>
<p>We can easily and (fairly) quickly do this for all 998 chemicals for which the 3-compartment steady-state model can be parameterized, using <code>sapply()</code> to loop over the chemicals. This will take a few minutes to run (for example, it takes about 10-15 minutes on a Dell Latitude with an Intel i7 processor).</p>
<p>In order to make the Monte Carlo sampling reproducible, set a seed for the random number generator. It doesn’t matter what seed you choose – it can be any integer. Here, the seed is set to 42, because it’s the answer to the ultimate question of life, the universe, and everything <a href="https://en.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy_(novel)">(Adams, 1979)</a>.</p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="toxicokinetic-modeling.html#cb416-1"></a><span class="kw">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb416-2"><a href="toxicokinetic-modeling.html#cb416-2"></a></span>
<span id="cb416-3"><a href="toxicokinetic-modeling.html#cb416-3"></a><span class="kw">system.time</span>(</span>
<span id="cb416-4"><a href="toxicokinetic-modeling.html#cb416-4"></a>  <span class="kw">suppressWarnings</span>(</span>
<span id="cb416-5"><a href="toxicokinetic-modeling.html#cb416-5"></a>    css_3compss &lt;-<span class="st"> </span><span class="kw">sapply</span>(chems_3compss<span class="op">$</span>CAS,</span>
<span id="cb416-6"><a href="toxicokinetic-modeling.html#cb416-6"></a>              calc_mc_css,</span>
<span id="cb416-7"><a href="toxicokinetic-modeling.html#cb416-7"></a>              <span class="co"># Additional arguments to calc_mc_css()</span></span>
<span id="cb416-8"><a href="toxicokinetic-modeling.html#cb416-8"></a>              <span class="dt">model =</span> <span class="st">&quot;3compartmentss&quot;</span>,</span>
<span id="cb416-9"><a href="toxicokinetic-modeling.html#cb416-9"></a>              <span class="dt">which.quantile =</span> <span class="kw">c</span>(<span class="fl">0.05</span>, <span class="fl">0.5</span>, <span class="fl">0.95</span>),</span>
<span id="cb416-10"><a href="toxicokinetic-modeling.html#cb416-10"></a>              <span class="dt">output.units =</span> <span class="st">&quot;uM&quot;</span>,</span>
<span id="cb416-11"><a href="toxicokinetic-modeling.html#cb416-11"></a>              <span class="dt">suppress.messages =</span> <span class="ot">TRUE</span>)</span>
<span id="cb416-12"><a href="toxicokinetic-modeling.html#cb416-12"></a>              )</span>
<span id="cb416-13"><a href="toxicokinetic-modeling.html#cb416-13"></a>)</span></code></pre></div>
<pre><code>##    user  system elapsed 
## 576.231  26.298 660.589</code></pre>
<p>Organizing the results:</p>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb418-1"><a href="toxicokinetic-modeling.html#cb418-1"></a><span class="co"># Css_3compss comes out as a 3 x 998 array,</span></span>
<span id="cb418-2"><a href="toxicokinetic-modeling.html#cb418-2"></a><span class="co"># Where rows are quantiles and columns are chemicals</span></span>
<span id="cb418-3"><a href="toxicokinetic-modeling.html#cb418-3"></a><span class="co"># Transpose it so that rows are chemicals and columns are quantiles</span></span>
<span id="cb418-4"><a href="toxicokinetic-modeling.html#cb418-4"></a>css_3compss &lt;-<span class="st"> </span><span class="kw">t</span>(css_3compss)</span>
<span id="cb418-5"><a href="toxicokinetic-modeling.html#cb418-5"></a><span class="co"># Convert to data.frame</span></span>
<span id="cb418-6"><a href="toxicokinetic-modeling.html#cb418-6"></a>css_3compss &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(css_3compss)</span>
<span id="cb418-7"><a href="toxicokinetic-modeling.html#cb418-7"></a><span class="co"># Make a column for CAS, rather than just leaving it as the row names</span></span>
<span id="cb418-8"><a href="toxicokinetic-modeling.html#cb418-8"></a>css_3compss<span class="op">$</span>CAS &lt;-<span class="st"> </span><span class="kw">row.names</span>(css_3compss)</span>
<span id="cb418-9"><a href="toxicokinetic-modeling.html#cb418-9"></a></span>
<span id="cb418-10"><a href="toxicokinetic-modeling.html#cb418-10"></a><span class="kw">head</span>(css_3compss) <span class="co">#View first few rows</span></span></code></pre></div>
<pre><code>##                 5%     50%     95%        CAS
## 2971-36-0    0.392   1.978   16.11  2971-36-0
## 94-75-7     32.950  97.100  385.20    94-75-7
## 94-82-6    133.700 473.100 2679.00    94-82-6
## 90-43-7     48.690 148.400  778.60    90-43-7
## 1007-28-9    2.777   7.028   24.69  1007-28-9
## 71751-41-2   2.311  10.240   73.59 71751-41-2</code></pre>
</div>
<div id="plotting-the-c_ss-dose-slope-distribution-quantiles" class="section level4">
<h4>Plotting the <span class="math inline">\(C_{ss}\)</span>-dose slope distribution quantiles</h4>
<p>Here, we will plot the resulting concentration distribution quantiles for each chemical, while sorting the chemicals from lowest to highest median value.</p>
<p>By default, <code>ggplot2</code> will plot the chemical CASRNs in alphabetically-sorted order. To force it to plot them in another order, we have to explicitly specify the desired order. The easiest way to do this is to add a column in the data.frame that contains the chemical names as a factor (categorical) variable, whose levels (categories) are explicitly set to be the CASRNs in our desired plotting order. Then we can tell <code>ggplot2</code> to plot that factor variable on the x-axis, rather than the original CASRN variable.</p>
<p>Set the ordering of the chemical CASRNs from lowest to highest median value:</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="toxicokinetic-modeling.html#cb420-1"></a>chemical_order &lt;-<span class="st"> </span><span class="kw">order</span>(css_3compss<span class="op">$</span><span class="st">`</span><span class="dt">50%</span><span class="st">`</span>)</span></code></pre></div>
<p>Create a factor (categorical) CAS column where the factor levels are given by the CASRNs with this ordering.</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="toxicokinetic-modeling.html#cb421-1"></a>css_3compss<span class="op">$</span>CAS_factor &lt;-<span class="st"> </span><span class="kw">factor</span>(css_3compss<span class="op">$</span>CAS, <span class="dt">levels =</span> css_3compss<span class="op">$</span>CAS[chemical_order])</span></code></pre></div>
<p>For plotting ease, reshape the data.frame into “long” format – rather than having one column for each quantile of the <span class="math inline">\(C_{ss}\)</span> distribution, have a row for each chemical/quantile combination. We use the <code>melt</code> function from the <code>reshape2</code> package.</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="toxicokinetic-modeling.html#cb422-1"></a>css_3compss_melt &lt;-<span class="st"> </span><span class="kw">melt</span>(css_3compss,</span>
<span id="cb422-2"><a href="toxicokinetic-modeling.html#cb422-2"></a>                                   <span class="dt">id.vars =</span> <span class="st">&quot;CAS_factor&quot;</span>,</span>
<span id="cb422-3"><a href="toxicokinetic-modeling.html#cb422-3"></a>                                   <span class="dt">measure.vars =</span> <span class="kw">c</span>(<span class="st">&quot;5%&quot;</span>, <span class="st">&quot;50%&quot;</span>, <span class="st">&quot;95%&quot;</span>),</span>
<span id="cb422-4"><a href="toxicokinetic-modeling.html#cb422-4"></a>                                   <span class="dt">variable.name =</span> <span class="st">&quot;Percentile&quot;</span>,</span>
<span id="cb422-5"><a href="toxicokinetic-modeling.html#cb422-5"></a>                                   <span class="dt">value.name =</span> <span class="st">&quot;Css_slope&quot;</span>)</span>
<span id="cb422-6"><a href="toxicokinetic-modeling.html#cb422-6"></a><span class="kw">head</span>(css_3compss_melt)</span></code></pre></div>
<pre><code>##   CAS_factor Percentile Css_slope
## 1  2971-36-0         5%     0.392
## 2    94-75-7         5%    32.950
## 3    94-82-6         5%   133.700
## 4    90-43-7         5%    48.690
## 5  1007-28-9         5%     2.777
## 6 71751-41-2         5%     2.311</code></pre>
<p>Plot the slope percentiles. Use a log scale for the y-axis because the slopes span orders of magnitude. Suppress the x-axis labels (the CASRNs) because they are not readable anyway.</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="toxicokinetic-modeling.html#cb424-1"></a><span class="kw">ggplot</span>(css_3compss_melt) <span class="op">+</span></span>
<span id="cb424-2"><a href="toxicokinetic-modeling.html#cb424-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x=</span>CAS_factor,</span>
<span id="cb424-3"><a href="toxicokinetic-modeling.html#cb424-3"></a>                 <span class="dt">y =</span> Css_slope,</span>
<span id="cb424-4"><a href="toxicokinetic-modeling.html#cb424-4"></a>                 <span class="dt">color =</span> Percentile)) <span class="op">+</span></span>
<span id="cb424-5"><a href="toxicokinetic-modeling.html#cb424-5"></a><span class="st">  </span><span class="kw">scale_color_brewer</span>(<span class="dt">palette =</span> <span class="st">&quot;Set2&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># Use better color scheme than default</span></span>
<span id="cb424-6"><a href="toxicokinetic-modeling.html#cb424-6"></a><span class="st">  </span><span class="kw">scale_y_log10</span>() <span class="op">+</span><span class="st"> </span><span class="co"># Use log scale for y axis</span></span>
<span id="cb424-7"><a href="toxicokinetic-modeling.html#cb424-7"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Chemical&quot;</span>) <span class="op">+</span></span>
<span id="cb424-8"><a href="toxicokinetic-modeling.html#cb424-8"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Css-dose slope (uM per mg/kg/day)&quot;</span>) <span class="op">+</span></span>
<span id="cb424-9"><a href="toxicokinetic-modeling.html#cb424-9"></a><span class="st">  </span><span class="kw">annotation_logticks</span>(<span class="dt">sides =</span> <span class="st">&quot;l&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># Add log ticks to y axis</span></span>
<span id="cb424-10"><a href="toxicokinetic-modeling.html#cb424-10"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="co"># Plot with white plot background instead of gray</span></span>
<span id="cb424-11"><a href="toxicokinetic-modeling.html#cb424-11"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_blank</span>(), <span class="co"># Suppress x-axis labels</span></span>
<span id="cb424-12"><a href="toxicokinetic-modeling.html#cb424-12"></a>        <span class="dt">panel.grid.major.x =</span> <span class="kw">element_blank</span>(), <span class="co"># Suppress vertical grid lines</span></span>
<span id="cb424-13"><a href="toxicokinetic-modeling.html#cb424-13"></a>        <span class="dt">legend.position =</span> <span class="kw">c</span>(<span class="fl">0.1</span>,<span class="fl">0.8</span>) <span class="co"># Place legend in lower right corner</span></span>
<span id="cb424-14"><a href="toxicokinetic-modeling.html#cb424-14"></a>        ) </span></code></pre></div>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-172-1.png" width="576" /></p>
<p>Chemicals along the x-axis are in order from lowest to highest median (50th percentile) predicted <span class="math inline">\(C_{ss}\)</span>-dose slope. The orange points represent that 50th percentile <span class="math inline">\(C_{ss}\)</span>-dose slope for each chemical. The green points represent the 5th percentile <span class="math inline">\(C_{ss}\)</span>-dose slopes, and the purple points represent the 95th percentile <span class="math inline">\(C_{ss}\)</span>-dose slope for each chemical. Each chemical has one orange point (50th percentile), one green point (5th percentile), and one purple point (95th percentile), characterizing the distribution of <span class="math inline">\(C_{ss}\)</span>-dose slopes across the U.S. population for that chemical. The width of the distribution for each chemical is roughly represented by the vertical distance between the green and purple points for that chemical.</p>
<p><br></p>
<div class="question">
<p><i>With this, we can answer <strong>Environmental Health Question 4</strong>:</i>
Considering the chemicals evaluated in the above TK modeling example, do the <span class="math inline">\(C_{ss}\)</span>-dose slope distributions become wider as the median <span class="math inline">\(C_{ss}\)</span>-dose slope increases?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: No – the <span class="math inline">\(C_{ss}\)</span>-dose slope distributions generally become narrower as the median <span class="math inline">\(C_{ss}\)</span>-dose slope increases. This can be seen by looking at the right end of the plot, where the highest-median chemicals are located – the distance between the green points and purple points, representing the 5th and 95th percentiles, are much smaller for these higher-median chemicals.</p>
</div>
<p><br></p>
</div>
<div id="reverse-tk-calculating-administered-equivalent-doses-for-toxcast-bioactive-concentrations" class="section level4">
<h4>Reverse TK: Calculating Administered Equivalent Doses for ToxCast Bioactive Concentrations</h4>
<p>As described in an earlier section of this document, the slope defining the linear relation between <span class="math inline">\(C_{ss}\)</span> and dose is useful for reverse toxicokinetics: converting an internal dose metric to an external dose metric. The internal dose metric may, for example, be a concentration associated with an <em>in vivo</em> health effect, or <em>in vitro</em> bioactivity. Here, we will consider <em>in vitro</em> bioactivity – specifically, from the ToxCast program. ToxCast tests chemicals in multiple concentration-response format across a battery of <em>in vitro</em> assays that measure activity in a wide variety of biological endpoints. If a chemical showed any activity in an assay at any of its tested concentrations, then one metric of concentration associated with bioactivity is AC50 – the concentration at which the assay response is halfway between its minimum and its maximum.</p>
<p>The module won’t address the details of how ToxCast determines assay activity and AC50s from raw concentration-response data. There is an entire R package for the ToxCast data processing workflow, called <code>tcpl</code>. If you want to learn more about those details, <a href="https://www.epa.gov/chemical-research/toxcast-data-generation-toxcast-pipeline-tcpl">start here</a>. Lots of information is available if you install the <code>tcpl</code> R package and look at the package vignette; it essentially walks you through the full ToxCast data processing workflow.</p>
<p>In this module, we will begin with pre-computed ToxCast AC50 values for various chemicals and assays. We will use <code>httk</code> to convert ToxCast AC50 values into administered equivalent doses (AEDs).</p>
</div>
<div id="loading-toxcast-ac50s" class="section level4">
<h4>Loading ToxCast AC50s</h4>
<p>The latest public release of ToxCast high-throughput screening assay data can be downloaded <a href="https://www.epa.gov/chemical-research/exploring-toxcast-data-downloadable-data">here</a>. Previous public releases of ToxCast data included a matrix of AC50s by chemical and assay. The data format of the latest public release does not contain this kind of matrix. So this dataset was pre-processed to prepare a simple data.frame of AC50s for each chemical/assay combination for the purposes of this training module.</p>
<p>Read in the pre-processed data set and view the first few rows.</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="toxicokinetic-modeling.html#cb425-1"></a>toxcast &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Module2_5/Module2_5_TK_Toxcast_Data.csv&quot;</span>)</span>
<span id="cb425-2"><a href="toxicokinetic-modeling.html#cb425-2"></a><span class="kw">head</span>(toxcast)</span></code></pre></div>
<pre><code>##                         Compound        CAS        DTXSID         aenm
## 1                  Acetohexamide   968-81-0 DTXSID7020007 ACEA_ER_80hr
## 2 2-Methoxyaniline hydrochloride   134-29-2 DTXSID8020092 ACEA_ER_80hr
## 3             Sodium L-ascorbate   134-03-2 DTXSID0020105 ACEA_ER_80hr
## 4                   Sodium azide 26628-22-8 DTXSID8020121 ACEA_ER_80hr
## 5               Benzotrichloride    98-07-7 DTXSID1020148 ACEA_ER_80hr
## 6                 Benzyl acetate   140-11-4 DTXSID0020151 ACEA_ER_80hr
##   log10_ac50
## 1  0.6524155
## 2 -1.3141432
## 3  0.8248535
## 4  1.9839338
## 5  1.8370790
## 6 -0.3299611</code></pre>
<p>The columns of this data frame are:</p>
<ul>
<li><p><code>Compound</code>: The compound name.</p></li>
<li><p><code>CAS</code>: The compound’s CASRN.</p></li>
<li><p><code>DTXSID</code>: The compound’s DSSTox Substance ID.</p></li>
<li><p><code>aenm</code>: Assay identifier. “aenm” stands for “Assay Endpoint Name.” More information about the ToxCast assays is available on the <a href="https://www.epa.gov/chemical-research/exploring-toxcast-data-downloadable-data">ToxCast data download page</a>.</p></li>
<li><p><code>log10_ac50</code>: The AC50 for the chemical/assay combination on each row, in log10 uM units.</p></li>
</ul>
<p>How many ToxCast chemicals are in this data set?</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="toxicokinetic-modeling.html#cb427-1"></a><span class="kw">length</span>(<span class="kw">unique</span>(toxcast<span class="op">$</span>DTXSID))</span></code></pre></div>
<pre><code>## [1] 7863</code></pre>
<p><br></p>
<div class="question">
<p><i>With this, we can answer <strong>Environmental Health Question 5</strong>:</i>
How many chemicals have available AC50 values to evaluate in the current ToxCast/Tox21 high-throughput screening database?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: 7863 chemicals.</p>
</div>
<p><br></p>
</div>
<div id="subsetting-the-toxcast-chemicals" class="section level4">
<h4>Subsetting the ToxCast Chemicals</h4>
<p>Not all of the ToxCast chemicals have TK data built into <code>httk</code> such that we can perform reverse TK using the HTTK models. Let’s subset the ToxCast data to include only the chemicals for which we can run the 3-compartment steady-state models.</p>
<p>Previously, we used <code>get_cheminfo()</code> to get a list of chemicals for which we could run the 3-compartment steady state model, including the names, CASRNs, and DSSTox IDs of those chemicals. That list is stored in variable <code>chems_3compss</code>, a data.frame with compound name, CASRN, and DTXSID. Now, we can use that chemical list to subset the ToxCast data.</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="toxicokinetic-modeling.html#cb429-1"></a>toxcast_httk &lt;-<span class="st"> </span><span class="kw">subset</span>(toxcast,</span>
<span id="cb429-2"><a href="toxicokinetic-modeling.html#cb429-2"></a>                       <span class="dt">subset =</span> toxcast<span class="op">$</span>DTXSID <span class="op">%in%</span></span>
<span id="cb429-3"><a href="toxicokinetic-modeling.html#cb429-3"></a><span class="st">                         </span>chems_3compss<span class="op">$</span>DTXSID)</span></code></pre></div>
<p>How many chemicals are in this subset?</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="toxicokinetic-modeling.html#cb430-1"></a><span class="kw">length</span>(<span class="kw">unique</span>(toxcast_httk<span class="op">$</span>DTXSID))</span></code></pre></div>
<pre><code>## [1] 911</code></pre>
<p>There were 998 <code>httk</code> chemicals for which we could run the 3-compartment steady-state model; only 911 of them had ToxCast data. Conversely, most of the 7863 ToxCast chemicals do not have TK data in <code>httk</code> such that we can run the 3-compartment steady state model.</p>
</div>
<div id="identifying-the-lower-bound" class="section level4">
<h4>Identifying the Lower-Bound</h4>
<p>ToxCast/Tox21 screens chemicals across multiple assays, such that each chemical has multiple resulting AC50 values, spanning a range of values. For example, here are boxplots of the AC50s for the first 20 chemicals listed in <code>chems_3compss</code>. Note that the chemical identifiers, DTXSID, are used here in these visualizations to represent unique chemicals.</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="toxicokinetic-modeling.html#cb432-1"></a><span class="kw">ggplot</span>(toxcast_httk[toxcast_httk<span class="op">$</span>DTXSID <span class="op">%in%</span></span>
<span id="cb432-2"><a href="toxicokinetic-modeling.html#cb432-2"></a><span class="st">                      </span>chems_3compss[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>,</span>
<span id="cb432-3"><a href="toxicokinetic-modeling.html#cb432-3"></a>                                    <span class="st">&quot;DTXSID&quot;</span>],</span>
<span id="cb432-4"><a href="toxicokinetic-modeling.html#cb432-4"></a>                    ]</span>
<span id="cb432-5"><a href="toxicokinetic-modeling.html#cb432-5"></a>       ) <span class="op">+</span></span>
<span id="cb432-6"><a href="toxicokinetic-modeling.html#cb432-6"></a><span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>DTXSID, <span class="dt">y =</span> log10_ac50)) <span class="op">+</span></span>
<span id="cb432-7"><a href="toxicokinetic-modeling.html#cb432-7"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;log10 AC50&quot;</span>) <span class="op">+</span></span>
<span id="cb432-8"><a href="toxicokinetic-modeling.html#cb432-8"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb432-9"><a href="toxicokinetic-modeling.html#cb432-9"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>,</span>
<span id="cb432-10"><a href="toxicokinetic-modeling.html#cb432-10"></a>                                   <span class="dt">hjust =</span> <span class="dv">1</span>))</span></code></pre></div>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-177-1.png" width="576" /></p>
<p>Sometimes we have an interest in getting the equivalent dose for an AC50 for one specific assay. For example, if we happen to be interested in estrogen-receptor activity, we might look specifically at one of the assays that measures estrogen receptor activity.</p>
<p>However, sometimes we just want a general idea of what concentrations showed bioactivity in <em>any</em> of the ToxCast assays, regardless of the specific biological endpoint of each assay. In this case, typically, we are interested in a “reasonable lower bound” of bioactive concentrations across assays for each chemical. Intuitively, we suspect that the very lowest AC50s for each chemical might represent false activity. Therefore, we often select the tenth percentile of ToxCast AC50s for each chemical as that “reasonable lower bound” on bioactive concentrations.</p>
<p>Let’s calculate the tenth percentile ToxCast AC50 for each chemical. Here, we use the base-R function <code>aggregate</code>, which groups a vector (specified in the <code>x</code> argument) by a list of factors (specified in the <code>by</code> argument), and applies a function to each group (specified in the <code>FUN</code> argument). You can add any extra arguments to the <code>FUN</code> function as named arguments to <code>aggregate</code>.</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="toxicokinetic-modeling.html#cb433-1"></a>toxcast_httk_P10 &lt;-<span class="st"> </span><span class="kw">aggregate</span>(<span class="dt">x =</span> toxcast_httk<span class="op">$</span>log10_ac50, <span class="co"># Aggregate the AC50s</span></span>
<span id="cb433-2"><a href="toxicokinetic-modeling.html#cb433-2"></a>                              <span class="dt">by =</span> <span class="kw">list</span>(<span class="dt">DTXSID =</span> toxcast_httk<span class="op">$</span>DTXSID), <span class="co"># Group AC50s by DTXSID</span></span>
<span id="cb433-3"><a href="toxicokinetic-modeling.html#cb433-3"></a>                              <span class="dt">FUN =</span> quantile, <span class="co"># The function to apply to each group</span></span>
<span id="cb433-4"><a href="toxicokinetic-modeling.html#cb433-4"></a>                              <span class="dt">prob =</span> <span class="fl">0.1</span>) <span class="co"># An argument to the quantile() function</span></span>
<span id="cb433-5"><a href="toxicokinetic-modeling.html#cb433-5"></a><span class="co"># By default the names of the output data.frame will be &#39;DTXSID&#39; and &#39;x&#39;</span></span>
<span id="cb433-6"><a href="toxicokinetic-modeling.html#cb433-6"></a><span class="co"># Let&#39;s change &#39;x&#39; to be a more informative name</span></span>
<span id="cb433-7"><a href="toxicokinetic-modeling.html#cb433-7"></a><span class="kw">names</span>(toxcast_httk_P10) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;DTXSID&quot;</span>, <span class="st">&quot;log10_ac50_P10&quot;</span>)</span></code></pre></div>
<p>Let’s transform the tenth-percentile AC50 values back to the natural scale (they are currently on the log10 scale) and put them in a new column <code>AC50</code>. These AC50s will be in uM.</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="toxicokinetic-modeling.html#cb434-1"></a>toxcast_httk_P10<span class="op">$</span>AC50 &lt;-<span class="st"> </span><span class="dv">10</span><span class="op">^</span>(toxcast_httk_P10<span class="op">$</span>log10_ac50_P10)</span></code></pre></div>
<p>View the first few rows:</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="toxicokinetic-modeling.html#cb435-1"></a><span class="kw">head</span>(toxcast_httk_P10)</span></code></pre></div>
<pre><code>##          DTXSID log10_ac50_P10        AC50
## 1 DTXSID0020022      0.8932512  7.82079968
## 2 DTXSID0020232      0.2903537  1.95143342
## 3 DTXSID0020286     -1.3763735  0.04203649
## 4 DTXSID0020311      1.1513461 14.16922669
## 5 DTXSID0020319     -0.1934652  0.64052306
## 6 DTXSID0020365      0.4308058  2.69653361</code></pre>
</div>
<div id="calculating-equivalent-doses-for-10th-percentile-toxcast-ac50s" class="section level4">
<h4>Calculating Equivalent Doses for 10th Percentile ToxCast AC50s</h4>
<p>We can calculate equivalent doses in one line of R code – again including all of the Monte Carlo for TK uncertainty and variability – just by using the <code>httk</code> function <code>calc_mc_oral_equiv()</code>.</p>
<p>Note that in <code>calc_mc_oral_equiv()</code>, the <code>which.quantile</code> argument refers to the quantile of the <span class="math inline">\(C_{ss}\)</span>-dose slope, not the quantile of the equivalent dose itself. So specifying <code>which.quantile = 0.95</code> will yield a <em>lower</em> equivalent dose than <code>which.quantile = 0.05</code>.</p>
<p>Under the hood, <code>calc_mc_oral_equiv()</code> first calls <code>calc_mc_css()</code> to get percentiles of the <span class="math inline">\(C_{ss}\)</span>-dose slope for a chemical. It then divides a user-specified target concentration (specified in argument <code>conc</code>) by each quantile of <span class="math inline">\(C_{ss}\)</span>-dose slope to get the equivalent dose corresponding to that target concentration for each slope quantile.</p>
<p>Here, we’re using the <code>mapply()</code> function in base R to call <code>calc_mc_oral_equiv()</code> in a loop over chemicals. This is because <code>calc_mc_oral_equiv()</code> requires two chemical-specific arguments – the chemical identifier and the concentration for which to compute the equivalent dose. <code>mapply()</code> lets us provide vectors of values for each argument (in the named arguments <code>dtxsid</code> and <code>conc</code>), and will automatically loop over those vectors. We also use the argument <code>MoreArgs</code>, a named list of additional arguments to the function in <code>FUN</code> that will be the same for every iteration of the loop. Note that this line of code takes a few minutes to run.</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="toxicokinetic-modeling.html#cb437-1"></a><span class="kw">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb437-2"><a href="toxicokinetic-modeling.html#cb437-2"></a></span>
<span id="cb437-3"><a href="toxicokinetic-modeling.html#cb437-3"></a><span class="kw">system.time</span>(</span>
<span id="cb437-4"><a href="toxicokinetic-modeling.html#cb437-4"></a>  <span class="kw">suppressWarnings</span>(</span>
<span id="cb437-5"><a href="toxicokinetic-modeling.html#cb437-5"></a>  toxcast_equiv_dose &lt;-<span class="st"> </span><span class="kw">mapply</span>(<span class="dt">FUN =</span> calc_mc_oral_equiv,</span>
<span id="cb437-6"><a href="toxicokinetic-modeling.html#cb437-6"></a>  <span class="dt">conc =</span> toxcast_httk_P10<span class="op">$</span>AC50,</span>
<span id="cb437-7"><a href="toxicokinetic-modeling.html#cb437-7"></a>    <span class="dt">dtxsid =</span> toxcast_httk_P10<span class="op">$</span>DTXSID,</span>
<span id="cb437-8"><a href="toxicokinetic-modeling.html#cb437-8"></a>  <span class="dt">MoreArgs =</span> <span class="kw">list</span>(<span class="dt">model =</span> <span class="st">&quot;3compartmentss&quot;</span>,  <span class="co"># Model to use</span></span>
<span id="cb437-9"><a href="toxicokinetic-modeling.html#cb437-9"></a>                  <span class="dt">which.quantile =</span> <span class="kw">c</span>(<span class="fl">0.05</span>, <span class="fl">0.5</span>, <span class="fl">0.95</span>), <span class="co"># Quantiles of Css-dose slope</span></span>
<span id="cb437-10"><a href="toxicokinetic-modeling.html#cb437-10"></a>                       <span class="dt">suppress.messages =</span> <span class="ot">TRUE</span>)</span>
<span id="cb437-11"><a href="toxicokinetic-modeling.html#cb437-11"></a>  )</span>
<span id="cb437-12"><a href="toxicokinetic-modeling.html#cb437-12"></a>)</span>
<span id="cb437-13"><a href="toxicokinetic-modeling.html#cb437-13"></a>)</span></code></pre></div>
<pre><code>##    user  system elapsed 
## 596.673  25.932 634.079</code></pre>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="toxicokinetic-modeling.html#cb439-1"></a><span class="co"># By default, the results are a 3 x 911 matrix, where rows are quantiles and columns are chemicals</span></span>
<span id="cb439-2"><a href="toxicokinetic-modeling.html#cb439-2"></a></span>
<span id="cb439-3"><a href="toxicokinetic-modeling.html#cb439-3"></a>toxcast_equiv_dose &lt;-<span class="st"> </span><span class="kw">t</span>(toxcast_equiv_dose) <span class="co"># Transpose so that rows are chemicals</span></span>
<span id="cb439-4"><a href="toxicokinetic-modeling.html#cb439-4"></a>toxcast_equiv_dose &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(toxcast_equiv_dose) <span class="co"># Convert to data.frame</span></span>
<span id="cb439-5"><a href="toxicokinetic-modeling.html#cb439-5"></a><span class="kw">head</span>(toxcast_equiv_dose) <span class="co"># Look at first few rows</span></span></code></pre></div>
<pre><code>##         5%     50%     95%
## 1  0.11240 0.04879 0.02014
## 2  2.19800 0.92350 0.38770
## 3  0.71010 0.19530 0.02780
## 4 38.85000 9.30300 1.82500
## 5  0.07269 0.03400 0.01391
## 6  2.82500 0.68510 0.13100</code></pre>
<p>Let’s add the DTXSIDs back into this data.frame.</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="toxicokinetic-modeling.html#cb441-1"></a>toxcast_equiv_dose<span class="op">$</span>DTXSID &lt;-<span class="st"> </span>toxcast_httk_P10<span class="op">$</span>DTXSID</span></code></pre></div>
<p>We can get the names of these chemicals by using the list of chemicals for which the 3-compartment steady-state model can be parameterized, which was stored in the variable `<code>chems_3compss</code>. In that dataframe, we have the compound name and CASRN corresponding to each DTXSID.</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="toxicokinetic-modeling.html#cb442-1"></a><span class="kw">head</span>(chems_3compss)</span></code></pre></div>
<pre><code>##                                                Compound        CAS
## 1 2,2-bis(4-hydroxyphenyl)-1,1,1-trichloroethane (hpte)  2971-36-0
## 2                                                 2,4-d    94-75-7
## 3                                                2,4-db    94-82-6
## 4                                        2-phenylphenol    90-43-7
## 5                                6-desisopropylatrazine  1007-28-9
## 6                                             Abamectin 71751-41-2
##          DTXSID
## 1 DTXSID8022325
## 2 DTXSID0020442
## 3 DTXSID7024035
## 4 DTXSID2021151
## 5 DTXSID0037495
## 6 DTXSID8023892</code></pre>
<p>Merge <code>chems_3compss</code> with <code>toxcast_equiv_dose</code>.</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="toxicokinetic-modeling.html#cb444-1"></a>toxcast_equiv_dose &lt;-<span class="st"> </span><span class="kw">merge</span>(chems_3compss,</span>
<span id="cb444-2"><a href="toxicokinetic-modeling.html#cb444-2"></a>                            toxcast_equiv_dose,</span>
<span id="cb444-3"><a href="toxicokinetic-modeling.html#cb444-3"></a>                            <span class="dt">by =</span> <span class="st">&quot;DTXSID&quot;</span>,</span>
<span id="cb444-4"><a href="toxicokinetic-modeling.html#cb444-4"></a>                            <span class="dt">all.x =</span> <span class="ot">FALSE</span>,</span>
<span id="cb444-5"><a href="toxicokinetic-modeling.html#cb444-5"></a>                            <span class="dt">all.y =</span> <span class="ot">TRUE</span>)</span>
<span id="cb444-6"><a href="toxicokinetic-modeling.html#cb444-6"></a></span>
<span id="cb444-7"><a href="toxicokinetic-modeling.html#cb444-7"></a><span class="kw">head</span>(toxcast_equiv_dose)</span></code></pre></div>
<pre><code>##          DTXSID                 Compound        CAS       5%     50%     95%
## 1 DTXSID0020022              Acifluorfen 50594-66-6  0.11240 0.04879 0.02014
## 2 DTXSID0020232                 Caffeine    58-08-2  2.19800 0.92350 0.38770
## 3 DTXSID0020286 3-chloro-4-methylaniline    95-74-9  0.71010 0.19530 0.02780
## 4 DTXSID0020311                  Monuron   150-68-5 38.85000 9.30300 1.82500
## 5 DTXSID0020319           Chlorothalonil  1897-45-6  0.07269 0.03400 0.01391
## 6 DTXSID0020365            Cyclosporin a 59865-13-3  2.82500 0.68510 0.13100</code></pre>
<p>To find the chemicals with the lowest equivalent doses at the 95th percentile level (corresponding to the most-sensitive 5% of the population), sort this data.frame in ascending order on the <code>95%</code> column.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="toxicokinetic-modeling.html#cb446-1"></a>toxcast_equiv_dose &lt;-<span class="st"> </span>toxcast_equiv_dose[<span class="kw">order</span>(toxcast_equiv_dose<span class="op">$</span><span class="st">`</span><span class="dt">95%</span><span class="st">`</span>), ]</span>
<span id="cb446-2"><a href="toxicokinetic-modeling.html#cb446-2"></a><span class="kw">head</span>(toxcast_equiv_dose, <span class="dv">10</span>) <span class="co"># First ten rows of sorted table</span></span></code></pre></div>
<pre><code>##            DTXSID                       Compound        CAS        5%       50%
## 8   DTXSID0020442                          2,4-d    94-75-7 1.844e-06 6.020e-07
## 765 DTXSID8023216        3,5,3&#39;-triiodothyronine  6893-02-3 2.632e-05 5.390e-07
## 55  DTXSID0026882                         Octane   111-65-9 3.075e-05 7.427e-06
## 384 DTXSID4020533                    1,4-dioxane   123-91-1 3.123e-05 9.191e-06
## 815 DTXSID8037594                     Secbumeton 26259-45-0 3.731e-05 8.713e-06
## 841 DTXSID9020453                       Dieldrin    60-57-1 2.846e-05 1.089e-05
## 335 DTXSID3031862         Perfluorohexanoic acid   307-24-4 7.192e-05 1.910e-05
## 764 DTXSID8023214                  Levothyroxine    51-48-9 5.392e-05 6.510e-06
## 143 DTXSID1026035 Sodium 2-mercaptobenzothiolate  2492-26-4 1.285e-04 2.812e-05
## 810 DTXSID8034665                       Imazapyr 81334-34-1 5.036e-05 2.327e-05
##           95%
## 8   1.440e-07
## 765 2.870e-07
## 55  1.292e-06
## 384 1.510e-06
## 815 1.558e-06
## 841 2.990e-06
## 335 3.095e-06
## 764 3.487e-06
## 143 4.057e-06
## 810 4.832e-06</code></pre>
<p><br></p>
<div class="question">
<p><i>With this, we can answer <strong>Environmental Health Question 6</strong>:</i>
What are the chemicals with the ten lowest predicted equivalent doses (for tenth-percentile ToxCast AC50s), for the most-sensitive 5% of the population?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: 2,4-d; 3,5,3’-triiodothyronine; Octane; 1,4-dioxane; Secbumeton; Dieldrin; Perfluorohexanoic acid; Levothyroxine; Sodium 2-mercaptobenzothiolate; and Imazapyr.</p>
</div>
<p><br></p>
</div>
<div id="comparing-equivalent-doses-estimated-to-elicit-toxicity-hazard-to-external-exposure-estimates-exposure-for-chemical-prioritization-by-bioactivity-exposure-ratios-bers" class="section level4">
<h4>Comparing Equivalent Doses Estimated to Elicit Toxicity (Hazard) to External Exposure Estimates (Exposure), for Chemical Prioritization by Bioactivity-Exposure Ratios (BERs)</h4>
<p>To estimate potential risk, hazard – in the form of the equivalent dose for the 10th percentile Toxcast AC50 – now needs to be compared to exposure. A quantitative metric for this comparison is the ratio of the lowest 5% of equivalent doses to the highest 5% of potential exposures. This metric is termed the Bioactivity-Exposure Ratio, or BER. Lower BER corresponds to higher potential risk. With BERs calculated for each chemical, we can ultimately rank all of the chemicals from lowest to highest BER, to achieve a chemical prioritization based on potential risk.</p>
</div>
<div id="human-exposure-estimates" class="section level4">
<h4>Human Exposure Estimates</h4>
<p>Here, we will use exposure estimates that have been inferred from CDC NHANES urinary biomonitoring data (Ring et al., 2019). These estimates consist of an estimated median, and estimated upper and lower 95% credible interval bounds representing uncertainty in that estimated median. These estimates are provided here in the following csv file:</p>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="toxicokinetic-modeling.html#cb448-1"></a>exposure &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Module2_5/Module2_5_TK_Exposure_Data.csv&quot;</span>)</span>
<span id="cb448-2"><a href="toxicokinetic-modeling.html#cb448-2"></a><span class="kw">head</span>(exposure) <span class="co"># View first few rows</span></span></code></pre></div>
<pre><code>##                                                                                   Compound
## 1                                        1,2,3,4,5,6-Hexachlorocyclohexane (mixed isomers)
## 2                                                                   1,2,4-Trichlorobenzene
## 3                                                                   1,3,5-Trichlorobenzene
## 4                                                                      1,3-Dichlorobenzene
## 5                                                                      1,4-Dichlorobenzene
## 6 2,3-Dihydro-2,2-dimethyl-7-benzofuryl 2,4-dimethyl-6-oxa-5-oxo-3-thia-2,4-diazadecanoate
##          DTXSID        CAS       Median        low95         up95
## 1 DTXSID7020687   608-73-1 1.237622e-07 1.144743e-10 8.464811e-06
## 2 DTXSID0021965   120-82-1 1.157387e-08 5.005691e-11 2.950528e-07
## 3 DTXSID8026195   108-70-3 8.970557e-08 1.292361e-10 2.563596e-06
## 4 DTXSID6022056   541-73-1 9.802174e-08 9.421797e-11 8.343616e-06
## 5 DTXSID1020431   106-46-7 9.050628e-05 8.456633e-05 9.731353e-05
## 6 DTXSID3052725 65907-30-4 4.245608e-08 1.070856e-10 1.236776e-06</code></pre>
</div>
<div id="merging-exposure-estimates-with-equivalent-dose-estimates-of-toxicity-hazard" class="section level4">
<h4>Merging Exposure Estimates with Equivalent Dose Estimates of Toxicity (Hazard)</h4>
<p>To calculate a BER for a chemical, it needs to have both an equivalent dose and an exposure estimate. Not all of the chemicals for which equivalent doses could be computed (<em>i.e.</em>, chemicals with both ToxCast AC50s and <code>httk</code> data) also have exposure estimates inferred from NHANES. Find out how many do.</p>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="toxicokinetic-modeling.html#cb450-1"></a><span class="kw">length</span>(<span class="kw">intersect</span>(toxcast_equiv_dose<span class="op">$</span>DTXSID, exposure<span class="op">$</span>DTXSID))</span></code></pre></div>
<pre><code>## [1] 62</code></pre>
<p>This means that, using the ToxCast AC50 data for bioactive concentrations, the NHANES urinary inference data for exposures, and the <code>httk</code> package to convert bioactive concentrations to equivalent doses, we can compute BERs for 62 chemicals.</p>
<p>Merge together the ToxCast equivalent doses and the exposure data into a single data frame. Keep only the chemicals that have data in both ToxCast equivalent doses and exposure data frames.</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="toxicokinetic-modeling.html#cb452-1"></a>hazard_exposure &lt;-<span class="st"> </span><span class="kw">merge</span>(toxcast_equiv_dose,</span>
<span id="cb452-2"><a href="toxicokinetic-modeling.html#cb452-2"></a>                         exposure,</span>
<span id="cb452-3"><a href="toxicokinetic-modeling.html#cb452-3"></a>                         <span class="dt">by =</span> <span class="st">&quot;DTXSID&quot;</span>,</span>
<span id="cb452-4"><a href="toxicokinetic-modeling.html#cb452-4"></a>                         <span class="dt">all =</span> <span class="ot">FALSE</span>)</span>
<span id="cb452-5"><a href="toxicokinetic-modeling.html#cb452-5"></a><span class="kw">head</span>(hazard_exposure) <span class="co"># View first few rows of result</span></span></code></pre></div>
<pre><code>##          DTXSID            Compound.x      CAS.x        5%       50%       95%
## 1 DTXSID0020442                 2,4-d    94-75-7 1.844e-06 6.020e-07 1.440e-07
## 2 DTXSID0021389           Trichlorfon    52-68-6 1.699e+01 4.308e+00 6.771e-01
## 3 DTXSID0024266     Pirimiphos-methyl 29232-93-7 6.481e+00 1.771e+00 2.849e-01
## 4 DTXSID1020431 &quot;1,4-dichlorobenzene&quot;   106-46-7 2.197e+00 2.802e-01 2.160e-02
## 5 DTXSID1020855      Methyl parathion   298-00-0 3.280e+00 5.750e-01 7.159e-02
## 6 DTXSID1021956  Di-n-octyl phthalate   117-84-0 2.222e-04 1.196e-04 7.091e-05
##                       Compound.y      CAS.y       Median        low95
## 1 2,4-Dichlorophenoxyacetic acid    94-75-7 6.349713e-06 3.100467e-06
## 2                    Trichlorfon    52-68-6 5.021397e-08 8.309014e-11
## 3              Pirimiphos-methyl 29232-93-7 2.569640e-07 1.765961e-10
## 4            1,4-Dichlorobenzene   106-46-7 9.050628e-05 8.456633e-05
## 5               Methyl parathion   298-00-0 7.396964e-08 1.559956e-10
## 6              Dioctyl phthalate   117-84-0 8.039695e-05 7.674705e-05
##           up95
## 1 1.815981e-05
## 2 3.302746e-06
## 3 6.640505e-05
## 4 9.731353e-05
## 5 3.575740e-06
## 6 8.422537e-05</code></pre>
</div>
<div id="plotting-hazard-and-exposure-together" class="section level4">
<h4>Plotting Hazard and Exposure Together</h4>
<p>We can visually compare the equivalent doses and the inferred exposure estimates by plotting them together.</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="toxicokinetic-modeling.html#cb454-1"></a><span class="kw">ggplot</span>(hazard_exposure) <span class="op">+</span></span>
<span id="cb454-2"><a href="toxicokinetic-modeling.html#cb454-2"></a><span class="st">  </span><span class="kw">geom_crossbar</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Compound.x, <span class="co"># Boxes for equivalent doses</span></span>
<span id="cb454-3"><a href="toxicokinetic-modeling.html#cb454-3"></a>                     <span class="dt">y =</span> <span class="st">`</span><span class="dt">50%</span><span class="st">`</span>,</span>
<span id="cb454-4"><a href="toxicokinetic-modeling.html#cb454-4"></a>                    <span class="dt">ymax =</span> <span class="st">`</span><span class="dt">5%</span><span class="st">`</span>,</span>
<span id="cb454-5"><a href="toxicokinetic-modeling.html#cb454-5"></a>                    <span class="dt">ymin =</span> <span class="st">`</span><span class="dt">95%</span><span class="st">`</span>,</span>
<span id="cb454-6"><a href="toxicokinetic-modeling.html#cb454-6"></a>                    <span class="dt">color =</span> <span class="st">&quot;Equiv. dose&quot;</span>)) <span class="op">+</span></span>
<span id="cb454-7"><a href="toxicokinetic-modeling.html#cb454-7"></a><span class="st">  </span><span class="kw">geom_crossbar</span>(<span class="kw">aes</span>( <span class="dt">x=</span> Compound.x, <span class="co"># Boxes for exposures</span></span>
<span id="cb454-8"><a href="toxicokinetic-modeling.html#cb454-8"></a>                     <span class="dt">y =</span> Median,</span>
<span id="cb454-9"><a href="toxicokinetic-modeling.html#cb454-9"></a>                     <span class="dt">ymax =</span> up95,</span>
<span id="cb454-10"><a href="toxicokinetic-modeling.html#cb454-10"></a>                     <span class="dt">ymin =</span> low95,</span>
<span id="cb454-11"><a href="toxicokinetic-modeling.html#cb454-11"></a>                     <span class="dt">color =</span> <span class="st">&quot;Exposure&quot;</span>)) <span class="op">+</span></span>
<span id="cb454-12"><a href="toxicokinetic-modeling.html#cb454-12"></a><span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;Equiv. dose&quot;</span> =<span class="st"> &quot;black&quot;</span>,</span>
<span id="cb454-13"><a href="toxicokinetic-modeling.html#cb454-13"></a>                                <span class="st">&quot;Exposure&quot;</span> =<span class="st"> &quot;Orange&quot;</span>),</span>
<span id="cb454-14"><a href="toxicokinetic-modeling.html#cb454-14"></a>                     <span class="dt">name =</span> <span class="ot">NULL</span>) <span class="op">+</span></span>
<span id="cb454-15"><a href="toxicokinetic-modeling.html#cb454-15"></a><span class="st">  </span><span class="kw">scale_x_discrete</span>(<span class="dt">label =</span> <span class="cf">function</span>(x) <span class="kw">str_trunc</span>(x, <span class="dv">20</span>)</span>
<span id="cb454-16"><a href="toxicokinetic-modeling.html#cb454-16"></a>                   ) <span class="op">+</span><span class="st"> </span><span class="co"># Truncate chemical names to 20 chars</span></span>
<span id="cb454-17"><a href="toxicokinetic-modeling.html#cb454-17"></a><span class="st">  </span><span class="kw">scale_y_log10</span>() <span class="op">+</span></span>
<span id="cb454-18"><a href="toxicokinetic-modeling.html#cb454-18"></a><span class="st">  </span><span class="kw">annotation_logticks</span>(<span class="dt">sides =</span> <span class="st">&quot;l&quot;</span>) <span class="op">+</span></span>
<span id="cb454-19"><a href="toxicokinetic-modeling.html#cb454-19"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Equiv. dose or Exposure, mg/kg/day&quot;</span>) <span class="op">+</span></span>
<span id="cb454-20"><a href="toxicokinetic-modeling.html#cb454-20"></a><span class="st"> </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb454-21"><a href="toxicokinetic-modeling.html#cb454-21"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>,</span>
<span id="cb454-22"><a href="toxicokinetic-modeling.html#cb454-22"></a>                                   <span class="dt">hjust =</span> <span class="dv">1</span>,</span>
<span id="cb454-23"><a href="toxicokinetic-modeling.html#cb454-23"></a>                                   <span class="dt">size =</span> <span class="dv">6</span>),</span>
<span id="cb454-24"><a href="toxicokinetic-modeling.html#cb454-24"></a>        <span class="dt">axis.title.x =</span> <span class="kw">element_blank</span>(),</span>
<span id="cb454-25"><a href="toxicokinetic-modeling.html#cb454-25"></a>        <span class="dt">legend.position =</span> <span class="st">&quot;top&quot;</span>)</span></code></pre></div>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-189-1.png" width="576" /></p>
</div>
</div>
<div id="calculating-bioactivity-exposure-ratios-bers" class="section level2">
<h2>Calculating Bioactivity-Exposure Ratios (BERs)</h2>
<p>The bioactivity-exposure ratio (BER) is simply the ratio of the lower-end equivalent dose (for the most-sensitive 5% of the population) divided by the upper-end estimated exposure (here, the upper bound on the inferred population median exposure). In the data frame <code>hazard_exposure</code> containing the hazard and exposure data, the lower-end equivalent dose is in column <code>95%</code> (corresponding to the 95th-percentile <span class="math inline">\(C_{ss}\)</span>-dose slope) and the upper-end exposure is in column <code>up95</code>. Calculate the BER, and assign the result to a new column in the <code>hazard_exposure</code> data frame called <code>BER</code>.</p>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="toxicokinetic-modeling.html#cb455-1"></a>hazard_exposure[[<span class="st">&quot;BER&quot;</span>]] &lt;-<span class="st"> </span>hazard_exposure[[<span class="st">&quot;95%&quot;</span>]]<span class="op">/</span>hazard_exposure[[<span class="st">&quot;up95&quot;</span>]]</span></code></pre></div>
<div id="prioritizing-chemicals-by-ber" class="section level4">
<h4>Prioritizing Chemicals by BER</h4>
<p>To prioritize chemicals according to potential risk, they can be sorted from lowest to highest BER. The lower the BER, the higher the priority.</p>
<p>Sort the rows of the data.frame from lowest to highest BER.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="toxicokinetic-modeling.html#cb456-1"></a>hazard_exposure &lt;-<span class="st"> </span>hazard_exposure[<span class="kw">order</span>(hazard_exposure<span class="op">$</span>BER), ]</span>
<span id="cb456-2"><a href="toxicokinetic-modeling.html#cb456-2"></a><span class="kw">head</span>(hazard_exposure)</span></code></pre></div>
<pre><code>##           DTXSID                    Compound.x    CAS.x        5%       50%
## 1  DTXSID0020442                         2,4-d  94-75-7 1.844e-06 6.020e-07
## 31 DTXSID5020607 Diethylhexyl phthalate (dehp) 117-81-7 6.281e-04 3.390e-04
## 6  DTXSID1021956          Di-n-octyl phthalate 117-84-0 2.222e-04 1.196e-04
## 21 DTXSID3022455            Dimethyl phthalate 131-11-3 7.205e-04 2.860e-04
## 27 DTXSID4022529                 Methylparaben  99-76-3 1.469e+00 3.129e-01
## 15 DTXSID2024086                        Ethion 563-12-2 8.594e-03 1.851e-03
##          95%                     Compound.y    CAS.y       Median        low95
## 1  1.440e-07 2,4-Dichlorophenoxyacetic acid  94-75-7 6.349713e-06 3.100467e-06
## 31 1.853e-04     Di(2-ethylhexyl) phthalate 117-81-7 9.343466e-04 9.133541e-04
## 6  7.091e-05              Dioctyl phthalate 117-84-0 8.039695e-05 7.674705e-05
## 21 5.946e-05             Dimethyl phthalate 131-11-3 1.413887e-05 1.314067e-05
## 27 4.052e-02                  Methylparaben  99-76-3 9.525392e-04 8.949158e-04
## 15 2.750e-04                         Ethion 563-12-2 9.440419e-08 1.456731e-10
##            up95        BER
## 1  1.815981e-05  0.0079296
## 31 9.546859e-04  0.1940952
## 6  8.422537e-05  0.8419079
## 21 1.520612e-05  3.9102678
## 27 1.013307e-03 39.9878903
## 15 4.885048e-06 56.2942274</code></pre>
<p>The hazard-exposure plot above showed chemicals in alphabetical order. It can be revised to show chemicals in order of priority, from lowest to highest BER.</p>
<p>First, create a categorical (factor) variable for the compound names, whose levels are in order of increasing BER. (Since we already sorted the data.frame in order of increasing BER, we can just take the compound names in the order that they appear.)</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="toxicokinetic-modeling.html#cb458-1"></a>hazard_exposure<span class="op">$</span>Compound_factor &lt;-<span class="st"> </span><span class="kw">factor</span>(hazard_exposure<span class="op">$</span>Compound.x,</span>
<span id="cb458-2"><a href="toxicokinetic-modeling.html#cb458-2"></a>                                          <span class="dt">levels =</span> hazard_exposure<span class="op">$</span>Compound.x)</span></code></pre></div>
<p>Now, make the same plot as before, but use <code>Compound_factor</code> as the x-axis variable instead of <code>Compound</code>.</p>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="toxicokinetic-modeling.html#cb459-1"></a><span class="kw">ggplot</span>(hazard_exposure) <span class="op">+</span></span>
<span id="cb459-2"><a href="toxicokinetic-modeling.html#cb459-2"></a><span class="st">  </span><span class="kw">geom_crossbar</span>(<span class="kw">aes</span>(<span class="dt">x =</span> Compound_factor, <span class="co"># Boxes for equivalent dose</span></span>
<span id="cb459-3"><a href="toxicokinetic-modeling.html#cb459-3"></a>                     <span class="dt">y =</span> <span class="st">`</span><span class="dt">50%</span><span class="st">`</span>,</span>
<span id="cb459-4"><a href="toxicokinetic-modeling.html#cb459-4"></a>                    <span class="dt">ymax =</span> <span class="st">`</span><span class="dt">5%</span><span class="st">`</span>,</span>
<span id="cb459-5"><a href="toxicokinetic-modeling.html#cb459-5"></a>                    <span class="dt">ymin =</span> <span class="st">`</span><span class="dt">95%</span><span class="st">`</span>,</span>
<span id="cb459-6"><a href="toxicokinetic-modeling.html#cb459-6"></a>                    <span class="dt">color =</span> <span class="st">&quot;Equiv. dose&quot;</span>)) <span class="op">+</span></span>
<span id="cb459-7"><a href="toxicokinetic-modeling.html#cb459-7"></a><span class="st">  </span><span class="kw">geom_crossbar</span>(<span class="kw">aes</span>( <span class="dt">x=</span> Compound_factor, <span class="co"># Boxes for exposure</span></span>
<span id="cb459-8"><a href="toxicokinetic-modeling.html#cb459-8"></a>                     <span class="dt">y =</span> Median,</span>
<span id="cb459-9"><a href="toxicokinetic-modeling.html#cb459-9"></a>                     <span class="dt">ymax =</span> up95,</span>
<span id="cb459-10"><a href="toxicokinetic-modeling.html#cb459-10"></a>                     <span class="dt">ymin =</span> low95,</span>
<span id="cb459-11"><a href="toxicokinetic-modeling.html#cb459-11"></a>                     <span class="dt">color =</span> <span class="st">&quot;Exposure&quot;</span>)) <span class="op">+</span></span>
<span id="cb459-12"><a href="toxicokinetic-modeling.html#cb459-12"></a><span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&quot;Equiv. dose&quot;</span> =<span class="st"> &quot;black&quot;</span>,</span>
<span id="cb459-13"><a href="toxicokinetic-modeling.html#cb459-13"></a>                                <span class="st">&quot;Exposure&quot;</span> =<span class="st"> &quot;Orange&quot;</span>),</span>
<span id="cb459-14"><a href="toxicokinetic-modeling.html#cb459-14"></a>                     <span class="dt">name =</span> <span class="ot">NULL</span>) <span class="op">+</span></span>
<span id="cb459-15"><a href="toxicokinetic-modeling.html#cb459-15"></a><span class="st">    </span><span class="kw">scale_x_discrete</span>(<span class="dt">label =</span> <span class="cf">function</span>(x) <span class="kw">str_trunc</span>(x, <span class="dv">20</span>)</span>
<span id="cb459-16"><a href="toxicokinetic-modeling.html#cb459-16"></a>                   ) <span class="op">+</span><span class="st"> </span><span class="co"># Truncate chemical names</span></span>
<span id="cb459-17"><a href="toxicokinetic-modeling.html#cb459-17"></a><span class="st">  </span><span class="kw">scale_y_log10</span>() <span class="op">+</span></span>
<span id="cb459-18"><a href="toxicokinetic-modeling.html#cb459-18"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Equiv. dose or Exposure, mg/kg/day&quot;</span>) <span class="op">+</span></span>
<span id="cb459-19"><a href="toxicokinetic-modeling.html#cb459-19"></a><span class="st">  </span><span class="kw">annotation_logticks</span>(<span class="dt">sides =</span> <span class="st">&quot;l&quot;</span>) <span class="op">+</span></span>
<span id="cb459-20"><a href="toxicokinetic-modeling.html#cb459-20"></a><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span></span>
<span id="cb459-21"><a href="toxicokinetic-modeling.html#cb459-21"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>,</span>
<span id="cb459-22"><a href="toxicokinetic-modeling.html#cb459-22"></a>                                   <span class="dt">hjust =</span> <span class="dv">1</span>,</span>
<span id="cb459-23"><a href="toxicokinetic-modeling.html#cb459-23"></a>                                   <span class="dt">size =</span> <span class="dv">6</span>),</span>
<span id="cb459-24"><a href="toxicokinetic-modeling.html#cb459-24"></a>        <span class="dt">axis.title.x =</span> <span class="kw">element_blank</span>(),</span>
<span id="cb459-25"><a href="toxicokinetic-modeling.html#cb459-25"></a>        <span class="dt">legend.position =</span> <span class="st">&quot;top&quot;</span>)</span></code></pre></div>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-193-1.png" width="576" /></p>
<p>Now, the chemicals are displayed in order of increasing BER. From left to right, you can visually see the distance increase between the lower bound of equivalent doses (the bottom of the black boxes) and the upper bound of exposure estimates (the top of the orange boxes). Since the y-axis is put on a log10 scale, the distance between the boxes corresponds to the BER. We can gather a lot of information from this plot!</p>
<p><br></p>
<div class="question">
<p><i>With this, we can answer <strong>Environmental Health Question 7</strong>:</i>
Based on httk modeling estimates, are chemicals with higher bioactivity-exposure ratios always less potent than chemicals with lower bioactivity-exposure ratios?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: No – some chemicals with high potency (low equivalent doses) demonstrate high BERs because they have relatively low human exposure estimates; and vice versa.</p>
</div>
<p><br>
:::question
<i>With this, we can answer <strong>Environmental Health Question 8</strong>:</i>
Based on httk modeling estimates, do chemicals with higher bioactivity-exposure ratios always have lower estimated exposures than chemicals with lower bioactivity-exposure ratios?
:::
:::answer
<strong>Answer</strong>: No – some chemicals with high estimated exposures have equivalent doses that are higher still, resulting in a high BER despite the higher estimated exposure. Likewise, some chemicals with low estimated exposures also have lower equivalent doses, resulting in a low BER despite the low estimated exposure.
:::</p>
<p><br></p>
<div class="question">
<p><i>With this, we can answer <strong>Environmental Health Question 9</strong>:</i>
How are chemical prioritization results different when using only hazard information vs. only exposure information vs. bioactivity-exposure ratios?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: When chemicals are prioritized solely on the basis of hazard, more-potent chemicals will be highly prioritized. However, if humans are never exposed to these chemicals, or exposure is extremely low compared to potency, then despite the high potency, the potential risk may be low. Conversely, if chemicals are prioritized solely on the basis of exposure, then ubiquitous chemicals will be highly prioritized. However, if these chemicals are inert and do not produce adverse effects, then despite the high exposure, the potential risk may be low. For these reasons, risk-based chemical prioritization efforts consider both hazard (toxicity) and exposure, for instance through bioactivity-exposure ratios.</p>
</div>
<p><br></p>
</div>
<div id="filling-hazard-and-exposure-data-gaps-to-prioritize-more-chemicals" class="section level4">
<h4>Filling Hazard and Exposure Data Gaps to Prioritize More Chemicals</h4>
<p>To calculate a BER for a chemical, both bioactivity and exposure data are required, as well as sufficient TK data to perform reverse TK. In this training module, bioactivity data came from ToxCast AC50s; exposure data consisted of exposure inferences made from NHANES urinary biomonitoring data; and TK data consisted of parameter values measured <em>in vitro</em> and built into the <code>httk</code> R package. The intersections are illustrated in an Euler diagram below. BERs can only be calculated for chemicals in the triple intersection.</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="toxicokinetic-modeling.html#cb460-1"></a>fit &lt;-<span class="st"> </span>eulerr<span class="op">::</span><span class="kw">euler</span>(<span class="kw">list</span>(<span class="st">&#39;ToxCast AC50s&#39;</span> =<span class="st"> </span><span class="kw">unique</span>(toxcast<span class="op">$</span>DTXSID),</span>
<span id="cb460-2"><a href="toxicokinetic-modeling.html#cb460-2"></a>                   <span class="st">&#39;HTTK&#39;</span> =<span class="st"> </span><span class="kw">unique</span>(chems_3compss<span class="op">$</span>DTXSID),</span>
<span id="cb460-3"><a href="toxicokinetic-modeling.html#cb460-3"></a>                   <span class="st">&#39;NHANES inferred exposure&#39;</span> =<span class="st"> </span><span class="kw">unique</span>(exposure<span class="op">$</span>DTXSID)</span>
<span id="cb460-4"><a href="toxicokinetic-modeling.html#cb460-4"></a>                   ),</span>
<span id="cb460-5"><a href="toxicokinetic-modeling.html#cb460-5"></a>                   <span class="dt">shape =</span> <span class="st">&quot;ellipse&quot;</span>)</span>
<span id="cb460-6"><a href="toxicokinetic-modeling.html#cb460-6"></a><span class="kw">plot</span>(fit,</span>
<span id="cb460-7"><a href="toxicokinetic-modeling.html#cb460-7"></a>     <span class="dt">legend =</span> <span class="ot">TRUE</span>,</span>
<span id="cb460-8"><a href="toxicokinetic-modeling.html#cb460-8"></a>                   <span class="dt">quantities =</span> <span class="ot">TRUE</span></span>
<span id="cb460-9"><a href="toxicokinetic-modeling.html#cb460-9"></a>              )</span></code></pre></div>
<p><img src="02-Chapter2_files/figure-html/unnamed-chunk-194-1.png" width="576" /></p>
<p>Clearly, it would be useful to gather more data to allow calculation of BERs for more chemicals.</p>
<p><br></p>
<div class="question">
<p><i>With this, we can answer <strong>Environmental Health Question 10</strong>:</i>
Of the three data sets used in this training module – bioactivity from ToxCast, TK data from <code>httk</code>, and exposure inferred from NHANES urinary biomonitoring – which one most limits the number of chemicals that can be prioritized using BERs?</p>
</div>
<div class="answer">
<p><strong>Answer</strong>: The exposure data set includes the fewest chemicals and is therefore the most limiting.</p>
</div>
<p><br></p>
<p>The exposure data set used in this training module is limited to chemicals for which NHANES did urinary biomonitoring for markers of exposure, which is a fairly small set of chemicals that were of interest to NHANES due to existing concerns about health effects of exposure, and/or other reasons. This data set was chosen because it is a convenient set of exposure estimates to use for demonstration purposes, but it could be expanded by including other sources of exposure data and exposure model predictions. Further discussion is beyond the scope of this training module, but as an example of this kind of high-throughput exposure modeling, see <a href="https://pubmed.ncbi.nlm.nih.gov/30516957/">Ring et al., 2019</a>.</p>
<p>It would additionally be useful to gather TK data for additional chemicals. <em>In vitro</em> measurement efforts are ongoing. Additonally, <em>in silico</em> modeling can produce useful predictions of TK properties to facilitate chemical prioritization. Efforts are ongoing to develop computational models to predict TK parameters from chemical structure and properties.</p>
</div>
</div>
<div id="concluding-remarks-10" class="section level2">
<h2>Concluding Remarks</h2>
<p>This training module provides an overview of toxicokinetic modeling using the <code>httk</code> R package, and its application to <em>in vitro</em>-<em>in vivo</em> extrapolation in the form of placing <em>in vitro</em> data in the context of exposure by calculating equivalent doses for <em>in vitro</em> bioactive concentrations.</p>
<p>We would like to acknowledge the developers of the httk package, as detailed below via the CRAN website:</p>
<p><img src="Module2_5/Module2_5_TK_httk_CRAN_image.png" width="574" style="display: block; margin: auto;" /></p>
<p>This module also summarizes the use of the Bioactivity-Exposure Ratio (BER) for chemical prioritization, and provides examples of calculating the BER and ranking chemicals accordingly.</p>
<p>Together, these approaches can be used to more efficiently identify chemicals present in the environment that pose a potential risk to human health.</p>
<p>For additional case studies that leverage TK and/or httk modeling techniques, see the following publications that also address environmental health questions:</p>
<ul>
<li><p>Breen M, Ring CL, Kreutz A, Goldsmith MR, Wambaugh JF. High-throughput PBTK models for in vitro to in vivo extrapolation. Expert Opin Drug Metab Toxicol. 2021 Aug;17(8):903-921. PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/34056988/">34056988</a>.</p></li>
<li><p>Klaren WD, Ring C, Harris MA, Thompson CM, Borghoff S, Sipes NS, Hsieh JH, Auerbach SS, Rager JE. Identifying Attributes That Influence In Vitro-to-In Vivo Concordance by Comparing In Vitro Tox21 Bioactivity Versus In Vivo DrugMatrix Transcriptomic Responses Across 130 Chemicals. Toxicol Sci. 2019 Jan 1;167(1):157-171. PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/30202884/">30202884</a>.</p></li>
<li><p>Pearce RG, Setzer RW, Strope CL, Wambaugh JF, Sipes NS. httk: R Package for High-Throughput Toxicokinetics. J Stat Softw. 2017;79(4):1-26. PMID <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6134854/">30220889</a>.</p></li>
<li><p>Ring CL, Pearce RG, Setzer RW, Wetmore BA, Wambaugh JF. Identifying populations sensitive to environmental chemicals by simulating toxicokinetic variability. Environ Int. 2017 Sep;106:105-118. PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/28628784/">28628784</a>.</p></li>
<li><p>Ring C, Sipes NS, Hsieh JH, Carberry C, Koval LE, Klaren WD, Harris MA, Auerbach SS, Rager JE. Predictive modeling of biological responses in the rat liver using in vitro Tox21 bioactivity: Benefits from high-throughput toxicokinetics. Comput Toxicol. 2021 May;18:100166. PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/34013136/">34013136</a>.</p></li>
<li><p>Rotroff DM, Wetmore BA, Dix DJ, Ferguson SS, Clewell HJ, Houck KA, Lecluyse EL, Andersen ME, Judson RS, Smith CM, Sochaski MA, Kavlock RJ, Boellmann F, Martin MT, Reif DM, Wambaugh JF, Thomas RS. Incorporating human dosimetry and exposure into high-throughput in vitro toxicity screening. Toxicol Sci. 2010 Oct;117(2):348-58. PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/20639261/">20639261</a>.</p></li>
<li><p>Wetmore BA, Wambaugh JF, Ferguson SS, Sochaski MA, Rotroff DM, Freeman K, Clewell HJ 3rd, Dix DJ, Andersen ME, Houck KA, Allen B, Judson RS, Singh R, Kavlock RJ, Richard AM, Thomas RS. Integration of dosimetry, exposure, and high-throughput screening data in chemical toxicity assessment. Toxicol Sci. 2012 Jan;125(1):157-74. PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/21948869/">21948869</a>.</p></li>
<li><p>Wambaugh JF, Wetmore BA, Pearce R, Strope C, Goldsmith R, Sluka JP, Sedykh A, Tropsha A, Bosgra S, Shah I, Judson R, Thomas RS, Setzer RW. Toxicokinetic Triage for Environmental Chemicals. Toxicol Sci. 2015 Sep;147(1):55-67. PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/26085347/">26085347</a>.</p></li>
<li><p>Wambaugh JF, Wetmore BA, Ring CL, Nicolas CI, Pearce RG, Honda GS, Dinallo R, Angus D, Gilbert J, Sierra T, Badrinarayanan A, Snodgrass B, Brockman A, Strock C, Setzer RW, Thomas RS. Assessing Toxicokinetic Uncertainty and Variability in Risk Prioritization. Toxicol Sci. 2019 Dec 1;172(2):235-251. doi: 10.1093/toxsci/kfz205. PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/31532498/">31532498</a>.</p></li>
</ul>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="omics-analyses-and-systems-biology.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="read-across-toxicity-predictions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["TAME_Toolkit.pdf", "TAME_Toolkit.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
